import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    'nav.features': '功能',
    'nav.pricing': '价格',
    'nav.login': '登录',
    'nav.signup': '立即开始',
    'hero.badge': '由 AI 驱动的交易表现',
    'hero.title': '发现您的交易',
    'hero.title.accent': '优势。',
    'hero.desc': 'TradeGrail 交易复盘日志，将您的交易数据转化为可执行的洞察。停止猜测，开始像机构一样交易。',
    'hero.cta': '立即开始免费试用',
    'hero.demo': '查看演示',
    'hero.stats.roi': '月均投资回报率',
    'hero.stats.profit_factor': '获利因子',
    'hero.stats.traders': '活跃交易者',
    'hero.stats.volume': '已分析交易量',
    'hero.stats.winrate': '平均胜率提升',
    'features.tag': '终极工具箱',
    'features.title': '掌控市场所需的',
    'features.title.accent': '一切。',
    'features.desc': 'TradeGrail 不仅仅是一个日志。它是一个全面的性能生态系统，旨在帮助您发现并保持自己的优势。',
    'features.bento.title': '为卓越性能而生',
    'features.bento.desc': '我们从底层重新构思了交易日志，旨在为你提供绝对的竞争优势。',
    'features.bento.ai.title': 'AI 驱动的优势发现',
    'features.bento.ai.desc': '我们的专利算法会扫描您的交易历史，识别出您甚至未察觉的高概率交易机会。',
    'features.bento.trust': '信任之选',
    'features.bento.trust.desc': '超过 200 名职业交易员使用',
    'features.bento.psych.tag': '心理分析',
    'features.bento.security.title': '银行级安全',
    'features.bento.security.desc': '端到端加密，确保您的交易数据永远属于您自己。',
    'features.bento.global.title': '全球市场',
    'features.bento.global.desc': '支持全球 100+ 券商，覆盖股票、期货、外汇及加密货币。',
    'mockup.title': '可视化您的',
    'mockup.title.accent': '成功之路。',
    'mockup.desc': '我们的仪表盘不仅美观，而且功能强大。每一个像素的设计都是为了帮助您发现模式并消除错误。',
    'mockup.feature1': '实时权益曲线追踪',
    'mockup.feature2': '自动错误标记',
    'mockup.feature3': '可定制的报告组件',
    'mobile.tag': '移动优先',
    'mobile.title': '随时随地',
    'mobile.title.accent': '复盘交易。',
    'mobile.desc': '不要等到坐在桌前。在世界任何地方复盘您的表现，标记您的情绪，并始终保持您的竞争优势。',
    'comparison.title': '停止使用电子表格。',
    'comparison.desc': 'Excel 是用来记账的。TradeGrail 是用来赢的。',
    'comparison.excel.title': '传统电子表格',
    'comparison.excel.f1': '手动数据录入（缓慢且易错）',
    'comparison.excel.f2': '缺乏深度过滤的静态图表',
    'comparison.excel.f3': '零心理或情绪追踪',
    'comparison.excel.f4': '没有自动化的优势发现',
    'comparison.excel.f5': '难以可视化权益曲线',
    'comparison.grail.title': 'TradeGrail 交易日志',
    'comparison.grail.f1': '一键自动同步券商数据',
    'comparison.grail.f2': '高级多变量过滤',
    'comparison.grail.f3': '集成的心理与错误矩阵',
    'comparison.grail.f4': 'AI 驱动的交易机会识别',
    'comparison.grail.f5': '实时交互式权益分析',
    'pricing.title': '简单透明的价格',
    'pricing.desc': '投资于你的优势。选择适合你交易风格的方案。',
    'pricing.currency': '¥',
    'pricing.starter.price': '0',
    'pricing.pro.price': '29',
    'pricing.pro.yearly_price': '199',
    'pricing.elite.price': '79',
    'pricing.elite.yearly_price': '599',
    'pricing.pro.yearly_price': '58',
    'pricing.elite.yearly_price': '118',
    'pricing.popular': '最受欢迎',
    'pricing.billing.monthly': '按月付费',
    'pricing.billing.yearly': '按年付费',
    'pricing.billing.save': '立省 15%',
    'pricing.plan.starter.name': '入门版 (STARTER)',
    'pricing.plan.starter.desc': '适合正在起步的新手交易者。',
    'pricing.plan.pro.name': '专业版 (PRO)',
    'pricing.plan.pro.desc': '我们最受欢迎的方案，专为严肃交易者设计。',
    'pricing.plan.elite.name': '精英版 (ELITE)',
    'pricing.plan.elite.desc': '为职业交易员和自营交易机构提供的高级功能。',
    'pricing.cta.trial': '开始 7 天免费试用',
    'pricing.feature.manual': '手动录入交易',
    'pricing.feature.analytics': '基础表现分析',
    'pricing.feature.account_1': '1 个交易账户',
    'pricing.feature.charts': '交互式图表',
    'pricing.feature.mobile': '移动端访问',
    'pricing.feature.sync': '自动券商同步 (80+ 券商)',
    'pricing.feature.ai_edge': 'AI 驱动的优势发现',
    'pricing.feature.psych': '心理与错误追踪',
    'pricing.feature.unlimited': '无限交易账户',
    'pricing.feature.filter': '高级多变量过滤',
    'pricing.feature.support': '优先邮件支持',
    'pricing.feature.white_label': '白标表现报告',
    'pricing.feature.api': '自定义 API 访问',
    'pricing.feature.review': '1对1表现评估',
    'pricing.feature.prop_firm': '自营交易机构仪表盘',
    'pricing.feature.manager': '专属客户经理',
    'pricing.feature.early_access': '新功能优先体验',
    'pricing.feature.onboarding': '专属入驻指导',
    'pricing.brokers.title': '与 80 多家券商和平台无缝同步',
    'pricing.compare.title': '方案对比',
    'pricing.compare.desc': '各层级功能的详细细分。',
    'pricing.compare.features': '功能',
    'pricing.compare.cat.core': '核心功能',
    'pricing.compare.cat.analytics': '高级分析',
    'pricing.compare.cat.reporting': '报告与支持',
    'pricing.compare.cat.enterprise': '企业与 API',
    'pricing.trust.security.title': '银行级安全',
    'pricing.trust.security.desc': '您的数据已加密',
    'pricing.trust.globe.title': '全球市场',
    'pricing.trust.globe.desc': '支持 100 多家券商',
    'pricing.trust.zap.title': '实时同步',
    'pricing.trust.zap.desc': '数据即时更新',
    'pricing.trust.users.title': '专业社区',
    'pricing.trust.users.desc': '加入 10,000 多名交易者',
    'pricing.faq.desc': '关于 TradeGrail 您需要了解的一切。',
    'pricing.faq.q4': '以后可以更换方案吗？',
    'pricing.faq.a4': '可以，您可以随时在账户设置中升级或降级您的方案。',
    'pricing.faq.q5': '提供免费试用吗？',
    'pricing.faq.a5': '是的，所有方案都提供 7 天免费试用。无需信用卡即可开始。',
    'brokers.sync': '与您喜爱的平台无缝同步',
    'mobile.app_store.label': 'App Store 下载',
    'mobile.google_play.label': 'Google Play 获取',
    'pricing.starter.name': '入门版',
    'pricing.starter.desc': '适合正在起步的新手交易者。',
    'pricing.starter.cta': '立即开始',
    'pricing.starter.f1': '手动录入交易',
    'pricing.starter.f2': '基础分析',
    'pricing.starter.f3': '1 个交易账户',
    'pricing.starter.f4': '社区访问',
    'pricing.pro.name': '专业版',
    'pricing.pro.desc': '适合正在进阶的职业交易者。',
    'pricing.pro.cta': '升级专业版',
    'pricing.pro.f1': '自动券商同步',
    'pricing.pro.f2': '高级 AI 分析',
    'pricing.pro.f3': '无限账户',
    'pricing.pro.f4': '心理矩阵',
    'pricing.pro.f5': '优先支持',
    'pricing.elite.name': '精英版',
    'pricing.elite.desc': '适合专业及自营交易员。',
    'pricing.elite.cta': '联系销售',
    'pricing.elite.f1': '自定义 API 访问',
    'pricing.elite.f2': '一对一表现评估',
    'pricing.elite.f3': '自营交易公司仪表盘',
    'pricing.elite.f4': '白标报告',
    'pricing.elite.f5': '专属客户经理',
    'features.bento.replay.title': '市场复盘',
    'features.bento.replay.desc': '在真实的市场条件下练习，无需真金白银。',
    'features.bento.psych.title': '心理矩阵',
    'features.bento.psych.desc': '追踪您的情绪状态，识别导致亏损的心理陷阱。',
    'features.bento.sync.title': '自动同步',
    'features.bento.sync.desc': '支持 100 多家券商，数据实时更新。',
    'testimonials.title': '听听他们的声音',
    'testimonials.desc': '真实的交易者，真实的结果。加入精英行列。',
    'testimonials.community.title': '加入全球顶尖交易者社区',
    'testimonials.community.desc': '自 2013 年以来，全球数千名交易者 choose to work with us, and we have always been the best trading journal among competitors.',
    'testimonials.quote1': 'TradeGrail 帮我发现了伦敦盘交易中的一个漏洞，那个漏洞每月让我损失 2000 美元。一天之内就赚回了订阅费。',
    'testimonials.quote2': '心理矩阵改变了游戏规则。我终于意识到我的 FOMO 与特定的新闻事件有关。这就像为我的交易请了一位心理医生。',
    'testimonials.quote3': '我试过 TraderSync 和 TradeZella。TradeGrail 的界面更快，AI 洞察确实具有可操作性。这是我今年最好的投资。',
    'testimonials.quote4': '非常喜欢用 @tradegrail 来记录我的交易。导入交易非常简单，数据结果也非常出色。我最成功的交易通常发生在美东时间周三中午 12 点。',
    'testimonials.quote5': '正在 @tradegrail 上复盘昨天的交易。图表复盘功能太棒了。这是在 $NVDA 上的一个空单（使用价内看跌期权）。效果非常好。',
    'testimonials.quote6': '@tradegrail 为你完成了所有的繁重工作。记录并复盘。冲洗，重复。停止整天分析市场，开始分析你自己。',
    'testimonials.quote7': '在最近的市场震荡中，我花了不少时间研究交易日志软件。在使用了几个月后，我发现 @tradegrail 对我来说最有用。也是一个很棒的 App。它有我用过最好的 IBKR 导入功能。',
    'testimonials.quote8': '日内交易者（股票和加密货币）一定要看看 TradeGrail。追踪数据并发现优势的最佳日志！',
    'testimonials.quote9': '@tradegrail 不仅产品惊艳，团队也非常优秀！他们在产品上投入的心血令人印象深刻！',
    'faq.title': '常见问题',
    'faq.q1': '你们支持哪些券商？',
    'faq.a1': '我们支持 100 多家券商，包括 MetaTrader 4/5、NinjaTrader、盈透证券 (Interactive Brokers) 等，支持自动同步或 CSV 上传。',
    'faq.q2': '我的数据安全吗？',
    'faq.a2': '是的。我们使用银行级加密，绝不与第三方共享您的交易数据。您的优势由您掌控。',
    'faq.q3': '我可以随时取消订阅吗？',
    'faq.a3': '当然可以。没有合同，没有隐藏费用。只需在仪表盘上一键取消。',
    'footer.cta.tag': 'AI 交易日志',
    'footer.cta.title': '提升您的交易策略',
    'footer.cta.desc': '如果您拥有一支完整的团队——分析师、规划师、风险经理——全心全意为您的成功服务，会怎样？有了 TradeGrail，您就拥有了这一切。',
    'footer.cta.button': '立即开始免费试用',
    'footer.product': '产品',
    'footer.company': '公司',
    'footer.support': '支持',
    'footer.legal': '法律信息',
    'footer.disclaimer1': 'TradeGrail 是一套全面的研究、分析和交易工具，旨在协助交易者和投资者做出自己的决策。我们不提供有关购买或出售特定证券的建议，也不提供交易或投资建议。交易具有重大风险，可能并不适合每位投资者。存在损失全部或超过初始投资的可能性。',
    'footer.disclaimer2': '本网站上出现的证言可能不代表其他客户或顾客，也不保证未来的表现或成功。',
    'footer.copyright': '© 2026 TradeGrail - 保留所有权利。',
    'footer.download.appstore': 'App Store 下载',
    'footer.download.googleplay': 'Google Play 获取',
    'footer.product.analytics': '分析',
    'footer.product.replay': '市场复盘模拟器',
    'footer.product.assistant': 'AI 表现助手',
    'footer.product.brokers': '支持的券商',
    'footer.product.pricing': '价格',
    'footer.product.whatsnew': '更新日志',
    'footer.company.about': '关于我们',
    'footer.company.reviews': '评价',
    'footer.company.blog': '博客',
    'footer.company.affiliate': '合作伙伴计划',
    'footer.support.help': '帮助中心',
    'footer.support.contact': '联系我们',
    'footer.support.tutorials': '教程',
    'footer.support.howto': '操作指南',
    'footer.support.glossary': '词汇表',
    'footer.legal.terms': '条款和条件',
    'footer.legal.billing': '账单和退款',
    'footer.legal.risk': '风险披露',
    'footer.legal.privacy': '隐私政策',
    'features.showcase.tag': '功能亮点',
    'features.showcase.dashboard.label': '仪表盘',
    'features.showcase.dashboard.title': '全方位交易概览',
    'features.showcase.dashboard.desc': '实时追踪您的账户表现、风险状态和 AI 驱动的交易洞察。',
    'features.showcase.analytics.label': '分析',
    'features.showcase.analytics.title': '精准交易分析',
    'features.showcase.analytics.desc': '深入剖析每一次执行。通过机构级指标和行为洞察识别您的优势。',
    'features.showcase.journal.label': '日志',
    'features.showcase.journal.title': '交互式交易日志',
    'features.showcase.journal.desc': '最直观的记录和复盘交易的方式。与您的券商自动同步。',
    'features.showcase.notebook.label': '笔记本',
    'features.showcase.notebook.title': '智能交易笔记',
    'features.showcase.notebook.desc': '通过富文本和图片支持，记录每笔交易的想法、情绪和市场背景。',
    'features.showcase.reporting.label': '报告',
    'features.showcase.reporting.title': '自动化表现报告',
    'features.showcase.reporting.desc': '一键生成专业的 PDF 报告，供投资者或个人复盘使用。',
    'features.showcase.backtesting.label': '回测',
    'features.showcase.backtesting.title': '高级回测引擎',
    'features.showcase.backtesting.desc': '以机构级精度在历史数据上测试您的策略。',
    'features.showcase.replay.label': '复盘',
    'features.showcase.replay.title': '市场回放模拟器',
    'features.showcase.replay.desc': '逐跳重温市场行情，磨练您的执行和时机把握。',
    'features.showcase.playbook.label': '策略库',
    'features.showcase.playbook.title': '交易策略库',
    'features.showcase.playbook.desc': '在集中的、可执行的策略库中定义您的交易机会、规则和风险参数。',
    'features.showcase.cta.try': '立即体验',
    'features.showcase.cta.docs': '查看文档',
    'mockup.dashboard.rank': '交易员段位',
    'mockup.dashboard.gold': '黄金',
    'mockup.dashboard.next_rank': '距离下一段位',
    'mockup.dashboard.platinum': '铂金',
    'mockup.dashboard.leaderboard': '查看全球排行榜',
    'mockup.dashboard.risk_status': '风控状态: 正常',
    'mockup.dashboard.safe': '正常',
    'mockup.dashboard.risk_desc': '您在允许的亏损范围内。',
    'mockup.dashboard.today_pl': '今日盈亏',
    'mockup.dashboard.limit': '限制',
    'mockup.dashboard.net_pl': '净盈亏',
    'mockup.dashboard.win_rate': '胜率',
    'mockup.dashboard.profit_factor': '获利因子',
    'mockup.dashboard.equity_curve': '资金曲线',
    'mockup.dashboard.initial': '初始',
    'mockup.dashboard.current_level': '当前等级',
    'mockup.dashboard.weekly_goal': '本周目标',
    'mockup.dashboard.goal_achieved': '达成目标！',
    'mockup.dashboard.current': '当前',
    'mockup.dashboard.target': '目标',
    'mockup.dashboard.total_xp': '累计获得 XP',
    'mockup.dashboard.view_history': '查看历史',
    'mockup.dashboard.todo': '行动清单',
    'mockup.dashboard.discipline': '纪律追踪',
    'mockup.dashboard.ai_insights': 'AI 洞察',
    'mockup.dashboard.strategy_perf': '策略表现',
    'mockup.dashboard.good_morning': '早安, 交易员! 👋',
    'mockup.dashboard.add_trade': '添加交易',
    'mockup.dashboard.charts': '图表',
    'mockup.dashboard.playbook': '策略库',
    'mockup.dashboard.psychology': '心理矩阵',
    'mockup.dashboard.social': '社交广场',
    'mockup.dashboard.academy': '交易学院',
    'mockup.dashboard.notifications': '通知',
    'mockup.dashboard.friends': '好友',
    'mockup.dashboard.guide': '新手引导',
    'mockup.dashboard.dark_mode': '深色模式',
    'mockup.dashboard.language': '语言',
    'mockup.dashboard.journal': '交易日志',
    'mockup.dashboard.reports': '表现报告',
    'mockup.dashboard.notebook': '交易笔记',
    'mockup.dashboard.calendar': '交易日历',
    'mockup.dashboard.all_time': '所有时间',
    'mockup.dashboard.all_accounts': '所有账户',
    'mockup.market.tokyo': '东京',
    'mockup.market.london': '伦敦',
    'mockup.market.new_york': '纽约',
    'mockup.market.closed': '休市',
    'mockup.market.open': '开市',
    'mockup.analysis.tag_reviewed': '标记为已复盘',
    'mockup.analysis.replay': '回放',
    'mockup.analysis.share': '分享',
    'mockup.analysis.net_pl': '净盈亏',
    'mockup.analysis.live': '实时',
    'mockup.analysis.direction': '方向',
    'mockup.analysis.long': '做多',
    'mockup.analysis.short': '做空',
    'mockup.analysis.contracts': '合约数量',
    'mockup.analysis.total_pl': '总盈亏',
    'mockup.analysis.strategy': '策略',
    'mockup.analysis.strategy_val': '回调测试',
    'mockup.analysis.mae_mfe': '最大不利/有利变动',
    'mockup.analysis.rating': '交易评分',
    'mockup.analysis.tp': '止盈目标',
    'mockup.analysis.sl': '止损位',
    'mockup.analysis.autosaved': '已自动保存',
    'mockup.analysis.annotation1': '检查您的入场和出场点',
    'mockup.analysis.annotation2': '输入您的止盈目标和止损位',
    'mockup.analysis.annotation3': '开始记录日志',
    'mockup.analysis.mistakes': '错误',
    'mockup.analysis.opportunities': '机会',
    'mockup.analysis.habits': '习惯',
    'mockup.analysis.mistake1': '入场过晚',
    'mockup.analysis.mistake2': '过早止盈',
    'mockup.analysis.opp1': '缺口推进',
    'mockup.analysis.habit1': '睡眠良好',
    'mockup.analysis.running_pl': '累计盈亏',
    'mockup.analysis.note_placeholder': '"价格触及流动性扫荡区并显示出强烈的拒绝信号。在 15 分钟回调测试时入场，信心十足..."',
    'mockup.journal.month': '二月 2026',
    'mockup.journal.today': '今天',
    'mockup.journal.total_pl': '总盈亏',
    'mockup.journal.total_trades': '总交易数',
    'mockup.journal.trades_count': '笔交易',
    'mockup.journal.trades': '笔交易',
    'mockup.journal.all_time': '所有日期',
    'mockup.journal.sun': '日',
    'mockup.journal.mon': '一',
    'mockup.journal.tue': '二',
    'mockup.journal.wed': '三',
    'mockup.journal.thu': '四',
    'mockup.journal.fri': '五',
    'mockup.journal.sat': '六',
    'mockup.journal.february': '二月',
    'mockup.journal.annotation1': '可视化您的每日表现',
    'mockup.journal.annotation2': '追踪您的交易习惯与错误',
    'mockup.notebook.new_folder': '新建文件夹',
    'mockup.notebook.new_note': '新建笔记',
    'mockup.notebook.folders': '文件夹',
    'mockup.notebook.all_notes': '所有笔记',
    'mockup.notebook.folder1': '交易笔记',
    'mockup.notebook.folder2': '季度目标',
    'mockup.notebook.folder3': '行动计划',
    'mockup.notebook.trading_notes': '交易笔记',
    'mockup.notebook.quarterly_goals': '季度目标',
    'mockup.notebook.action_plans': '行动计划',
    'mockup.notebook.daily_journal': '每日日志',
    'mockup.notebook.weekly_review': '每周复盘',
    'mockup.notebook.monthly_summary': '每月总结',
    'mockup.notebook.daily_logs': '每日日志',
    'mockup.notebook.weekly_reviews': '每周复盘',
    'mockup.notebook.monthly_summaries': '每月总结',
    'mockup.notebook.chart_analysis': '图表分析',
    'mockup.notebook.templates': '模板库',
    'mockup.notebook.tags': '标签',
    'mockup.notebook.tag_high_win': '高胜率',
    'mockup.notebook.tag_fomo': 'FOMO',
    'mockup.notebook.trash': '回收站',
    'mockup.notebook.search': '搜索笔记 (F6)',
    'mockup.notebook.search_placeholder': '搜索笔记',
    'mockup.notebook.select_all': '全选',
    'mockup.notebook.created_at': '创建于',
    'mockup.notebook.updated_at': '更新于',
    'mockup.notebook.autosave': '自动保存',
    'mockup.notebook.link_trades': '关联交易',
    'mockup.notebook.add_tag': '添加标签',
    'mockup.notebook.save_template': '存为模板',
    'mockup.notebook.save_as_template': '存为模板',
    'mockup.notebook.body': '正文',
    'mockup.notebook.h1': '标题 1',
    'mockup.notebook.h2': '标题 2',
    'mockup.notebook.key_insight': '关键洞察',
    'mockup.notebook.insight_desc': '等待确认比盲目预测入场要稳健得多。在流动性被扫荡后，订单流的转变是入场的最佳时机。',
    'mockup.notebook.emotional_state': '情绪状态：冷静，专注。没有因为之前的亏损而急于入场。严格遵守了交易计划中的风险参数。',
    'mockup.notebook.ai_insight': 'AI 策略洞察',
    'mockup.notebook.ai_suggest': '建议添加 "流动性扫荡"',
    'mockup.notebook.ai_suggestion': '建议添加 "流动性扫荡"',
    'mockup.notebook.annotation1': '沉浸式富文本编辑器',
    'mockup.notebook.annotation2': '一键关联您的实盘交易',
    'mockup.notebook.note1_title': '发发发',
    'mockup.notebook.note2_title': '2026-03-01 复盘',
    'mockup.notebook.note3_title': '季度交易目标设定',
    'mockup.notebook.note4_title': '突破策略优化方案',
    'mockup.notebook.note5_title': '心理状态追踪',
    'mockup.notebook.note_content1': '今天在 1000SATS/USDT 的 15 分钟图表上观察到了一个完美的流动性扫荡模式。',
    'mockup.notebook.note_content2': '价格触及了之前的波动高点，然后迅速回落，形成了一个强烈的看跌拒绝信号。我在回调测试 50% 斐波那契位时入场做空。',
    'mockup.notebook.content_p1': '今天在 1000SATS/USDT 的 15 分钟图表上观察到了一个完美的流动性扫荡模式。',
    'mockup.notebook.content_p2': '价格触及了之前的波动高点，然后迅速回落，形成了一个强烈的看跌拒绝信号。我在回调测试 50% 斐波那契位时入场做空。',
    'mockup.notebook.content_insight': '等待确认比盲目预测入场要稳健得多。在流动性被扫荡后，订单流的转变是入场的最佳时机。',
    'mockup.notebook.content_p3': '情绪状态：冷静，专注。没有因为之前的亏损而急于入场。严格遵守了交易计划中的风险参数。',
    'mockup.reports.title': '表现报告',
    'mockup.reports.filter': '筛选',
    'mockup.reports.generate': '生成报告',
    'mockup.reports.export': '导出 PDF',
    'mockup.reports.stats_title': '报表统计',
    'mockup.reports.best_month': '最佳月份',
    'mockup.reports.best_month_sub': '历史最佳表现',
    'mockup.reports.best_month_desc': '历史最佳表现',
    'mockup.reports.worst_month': '最差月份',
    'mockup.reports.worst_month_sub': '最大回撤周期',
    'mockup.reports.worst_month_desc': '最大回撤周期',
    'mockup.reports.avg_month': '月均盈亏',
    'mockup.reports.avg_monthly': '月均盈亏',
    'mockup.reports.avg_month_sub': '平均基准水平',
    'mockup.reports.avg_monthly_desc': '平均基准水平',
    'mockup.reports.stats_data': '统计数据 (所有日期)',
    'mockup.reports.detailed_stats': '统计数据',
    'mockup.reports.total_pl': '总盈亏',
    'mockup.reports.avg_hold_loss': '平均持仓时间 (亏损)',
    'mockup.reports.avg_hold_even': '平均持仓时间 (持平)',
    'mockup.reports.avg_vol': '日均交易量',
    'mockup.reports.avg_daily_vol': '日均交易量',
    'mockup.reports.avg_win': '平均盈利',
    'mockup.reports.avg_trade_pl': '每笔平均盈亏',
    'mockup.reports.avg_pl_per_trade': '每笔平均盈亏',
    'mockup.reports.avg_loss': '平均亏损',
    'mockup.reports.pf': '盈亏比 (PF)',
    'mockup.reports.profit_factor': '盈亏比 (PF)',
    'mockup.reports.total_trades': '总交易笔数',
    'mockup.reports.open_trades': '持仓中',
    'mockup.reports.open_positions': '持仓中',
    'mockup.reports.win_trades': '盈利笔数',
    'mockup.reports.winning_trades': '盈利笔数',
    'mockup.reports.total_days': '总交易天数',
    'mockup.reports.loss_trades': '亏损笔数',
    'mockup.reports.losing_trades': '亏损笔数',
    'mockup.reports.win_days': '盈利天数',
    'mockup.reports.winning_days': '盈利天数',
    'mockup.reports.even_trades': '持平笔数',
    'mockup.reports.loss_days': '亏损天数',
    'mockup.reports.losing_days': '亏损天数',
    'mockup.reports.max_win_streak': '最大连胜',
    'mockup.reports.even_days': '持平天数',
    'mockup.reports.max_loss_streak': '最大连败',
    'mockup.reports.recorded_days': '记录天数',
    'mockup.reports.commissions': '手续费总额',
    'mockup.reports.total_fees': '手续费总额',
    'mockup.reports.max_win_days': '最长连红天数',
    'mockup.reports.max_green_streak': '最长连红天数',
    'mockup.reports.swap': '隔夜费',
    'mockup.reports.overnight_fees': '隔夜费',
    'mockup.reports.max_loss_days': '最长连黑天数',
    'mockup.reports.max_red_streak': '最长连黑天数',
    'mockup.reports.max_win': '最大单笔盈利',
    'mockup.reports.avg_daily_pl': '日均盈亏',
    'mockup.reports.max_loss': '最大单笔亏损',
    'mockup.showcase.integrations': '80+ 交易平台无缝同步',
    'mockup.showcase.see_all': '查看所有集成',
    'mockup.showcase.import': '导入交易',
    'mockup.showcase.dashboard': '仪表盘',
    'mockup.showcase.edit_layout': '编辑布局',
    'mockup.showcase.recent_shared': '您最近分享的交易',
    'mockup.showcase.largest_gain': '最大盈利',
    'mockup.showcase.total_gain_loss': '总盈亏额',
    'mockup.showcase.k_ratio': 'K 比率',
    'mockup.showcase.hourly': '分时统计',
    'mockup.showcase.search': '搜索',
    'mockup.showcase.plan_gold': '段位: 黄金',
    'mockup.showcase.days_30': '30 天',
    'mockup.showcase.days_60': '60 天',
    'mockup.showcase.days_90': '90 天',
    'mockup.showcase.custom': '自定义',
    'mockup.showcase.today': '今天',
    'mockup.showcase.may_2024': '五月, 2024',
    'mockup.showcase.community': '交易社区',
    'mockup.showcase.new_trade': '新建交易',
    'mockup.interactive.system_title': '实时权益分析系统',
    'mockup.interactive.initial_capital': '初始资金',
    'mockup.interactive.strategy_analysis': '策略胜率多维分析',
    'mockup.interactive.live_feed': '实时数据流',
    'mockup.interactive.ai_insights': 'AI 智能决策洞察',
    'mockup.interactive.insight1': '核心错误：执行犹豫',
    'mockup.interactive.insight2': '高胜率设置：斐波那契回撤 (67%)',
    'mockup.interactive.insight3': '优化提示：严格执行进场标准',
    'mockup.interactive.strategy1': '斐波那契回撤',
    'mockup.interactive.strategy2': '支撑位反弹',
    'mockup.interactive.strategy3': '突破策略',
    'mockup.interactive.strategy4': '新闻事件',
    'mockup.interactive.strategy5': '缺口回补',
    'mockup.interactive.strategy6': '趋势回调',
    'mockup.interactive.strategy7': '流动性扫荡',
    'mockup.interactive.strategy8': '趋势跟随',
    'mockup.reports.equity_curve_title': '每日累计净盈亏 (资金曲线)',
    'mockup.reports.daily_pl_title': '每日净盈亏',
    'mockup.reports.hours': '小时',
    'mockup.reports.minutes': '分',
    'playbook.title': '交易策略库',
    'playbook.search': '搜索策略... (F6)',
    'playbook.create': '创建新策略',
    'playbook.learn_more': '了解更多',
    'playbook.trades': '笔交易',
    'playbook.private': '私有',
    'playbook.public': '公开',
    'playbook.win_rate': '胜率',
    'playbook.net_pl': '净盈亏',
    'playbook.view_details': '查看详情',
    'playbook.sort': '排序:',
    'playbook.all_categories': '所有类别',
    'playbook.long_only': '仅做多',
    'playbook.short_only': '仅做空',
    'playbook.define_edge': '定义您的优势',
    'playbook.strat.breakout.title': '突破策略',
    'playbook.strat.breakout.desc': '当价格带量突破关键阻力位时入场。',
    'playbook.strat.gap.title': '缺口推进',
    'playbook.strat.gap.desc': '针对盘前跳空高开股票的日内交易策略。',
    'playbook.strat.sweep.title': '流动性扫荡',
    'playbook.strat.sweep.desc': '在波动高/低点上方的止损被触发后的反转设置。',
    'playbook.strat.bounce.title': '支撑位反弹',
    'playbook.strat.bounce.desc': '在经过验证的需求区或支撑位买入。',
    'playbook.strat.pullback.title': '趋势回调',
    'playbook.strat.pullback.desc': '在价格回调至均衡位置后，顺应趋势方向入场。',
    'auth.login.title': '欢迎回到 TradeGrail',
    'auth.login.desc': '继续您的系统化交易之路，充满信心。',
    'auth.login.email_label': '邮箱或用户名',
    'auth.login.password_label': '密码',
    'auth.login.forgot_password': '忘记密码？',
    'auth.login.submit': '登录',
    'auth.login.no_account': '还没有账号？',
    'auth.login.create_account': '创建账号',
    'auth.signup.title': '激活您的个人 AI 分析师',
    'auth.signup.desc': '您的系统化交易之路从现在开始。',
    'auth.signup.first_name_label': '名字',
    'auth.signup.email_label': '邮箱',
    'auth.signup.username_label': '用户名',
    'auth.signup.password_label': '密码',
    'auth.signup.agree_terms': '我同意',
    'auth.signup.terms_link': '条款和条件',
    'auth.signup.submit': '注册',
    'auth.signup.has_account': '已经是用户？',
    'auth.signup.sign_in': '登录',
    'auth.signup.error_terms': '请同意条款和条件',
    'auth.tags.analyze': '分析',
    'auth.tags.backtest': '回测',
    'auth.tags.ai_analyst': 'AI 分析师',
    'auth.google_button': '使用 Google 继续',
    'auth.or_divider': '或',
    'auth.login.email_placeholder': '请输入邮箱',
    'auth.login.password_placeholder': '请输入密码',
    'auth.login.error_failed': '登录失败，请检查邮箱和密码',
    'auth.login.error_google': 'Google 登录失败',
    'auth.signup.first_name_placeholder': '请输入名字',
    'auth.signup.email_placeholder': '请输入邮箱',
    'auth.signup.username_placeholder': '请输入用户名',
    'auth.signup.password_placeholder': '请输入密码',
    'auth.signup.confirm_password_label': '确认密码',
    'auth.signup.confirm_password_placeholder': '请再次输入密码',
    'auth.signup.error_password_mismatch': '两次输入的密码不一致',
    'auth.signup.error_failed': '注册失败，请稍后重试',
    'auth.signup.error_google': 'Google 注册失败',
    'auth.confirm.title': '确认邮件已发送',
    'auth.confirm.desc': '我们已将确认链接发送至',
    'auth.confirm.desc2': '请点击邮件中的链接完成注册。',
    'auth.confirm.spam': '没收到？请检查垃圾邮件文件夹。',
    'auth.confirm.resend': '重新发送确认邮件',
    'auth.confirm.resent': '确认邮件已重新发送！',
    'auth.confirm.go_login': '已完成确认？立即登录',
    'nav.features.journal.title': 'AI 智能仪表盘',
    'nav.features.journal.desc': '实时分析交易数据，获取 AI 驱动的深度市场洞察。',
    'nav.features.backtest.title': '策略回测引擎',
    'nav.features.backtest.desc': '利用海量历史数据，严谨验证您的交易策略。',
    'nav.features.spaces.title': '交易剧本 (Playbook)',
    'nav.features.spaces.desc': '系统化构建您的交易规则，实现纪律化执行。',
    'nav.features.prop.title': 'AI 市场分析师',
    'nav.features.prop.desc': '集成 Gemini 3.1 Pro，为您提供专业的实时市场分析。',
    'nav.features.replay.title': '市场脉动',
    'nav.features.replay.desc': '实时监控全球市场行情与交易情绪。',
    'nav.features.university.title': 'TradeGrail 学院',
    'nav.features.university.desc': '从零开始，掌握系统化交易的核心逻辑。',
    'nav.features.ai.title': '自营交易行同步',
    'nav.features.ai.desc': '统一管理您的自营账户，实时追踪进度与风险。',
    'nav.features.coming_soon': '即将推出',
    'pricing.crypto.title': '加密货币支付',
    'pricing.crypto.desc': '我们现在支持通过主流加密货币进行支付，包括 BTC、ETH 和 USDT。',
    'checkout.title': '结账',
    'checkout.order_summary': '订单摘要',
    'checkout.payment_details': '付款详情',
    'checkout.email': '电子邮箱',
    'checkout.card_number': '卡号',
    'checkout.expiry': '有效期',
    'checkout.cvc': 'CVC',
    'checkout.pay_now': '立即支付',
    'checkout.crypto_option': '使用加密货币支付',
    'checkout.secure_payment': '安全支付保障',
    'checkout.total': '总计',
    'checkout.back': '返回价格页面',
  },
  en: {
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.login': 'Login',
    'nav.signup': 'Get Started',
    'hero.badge': 'AI-POWERED TRADING PERFORMANCE',
    'hero.title': 'Discover Your Trading',
    'hero.title.accent': 'Edge.',
    'hero.desc': 'TradeGrail transforms your trading data into actionable insights. Stop guessing and start trading like an institution.',
    'hero.cta': 'Start Free Trial Now',
    'hero.demo': 'View Demo',
    'hero.stats.roi': 'Avg. Monthly ROI',
    'hero.stats.profit_factor': 'Profit Factor',
    'hero.stats.traders': 'Active Traders',
    'hero.stats.volume': 'Volume Analyzed',
    'hero.stats.winrate': 'Avg. Win Rate Boost',
    'features.tag': 'ULTIMATE TOOLBOX',
    'features.title': 'Everything you need to',
    'features.title.accent': 'Master the Market.',
    'features.desc': 'TradeGrail is more than just a journal. It is a comprehensive performance ecosystem designed to help you discover and maintain your edge.',
    'features.bento.title': 'Built for Peak Performance',
    'features.bento.desc': 'We reimagined the trading journal from the ground up to give you an absolute competitive advantage.',
    'features.bento.ai.title': 'AI-Driven Edge Discovery',
    'features.bento.ai.desc': 'Our proprietary algorithms scan your trading history to identify high-probability opportunities you might not even notice.',
    'features.bento.trust': 'TRUSTED BY PROS',
    'features.bento.trust.desc': 'Used by over 200 professional traders',
    'features.bento.psych.tag': 'PSYCHOLOGY ANALYSIS',
    'features.bento.security.title': 'Bank-Grade Security',
    'features.bento.security.desc': 'End-to-end encryption ensures your trading data always belongs to you.',
    'features.bento.global.title': 'Global Markets',
    'features.bento.global.desc': 'Support for 100+ brokers worldwide, covering stocks, futures, forex, and crypto.',
    'mockup.title': 'Visualize Your',
    'mockup.title.accent': 'Path to Success.',
    'mockup.desc': 'Our dashboard is not just beautiful, it is powerful. Every pixel is designed to help you discover patterns and eliminate mistakes.',
    'mockup.feature1': 'Real-time Equity Curve Tracking',
    'mockup.feature2': 'Automatic Error Tagging',
    'mockup.feature3': 'Customizable Reporting Widgets',
    'mobile.tag': 'MOBILE FIRST',
    'mobile.title': 'Review Trades',
    'mobile.title.accent': 'Anywhere, Anytime.',
    'mobile.desc': "Don't wait until you're at your desk. Review your performance, tag your emotions, and maintain your competitive edge from anywhere in the world.",
    'comparison.title': 'Stop Using Spreadsheets.',
    'comparison.desc': 'Excel is for accounting. TradeGrail is for winning.',
    'comparison.excel.title': 'Traditional Spreadsheets',
    'comparison.excel.f1': 'Manual data entry (slow and error-prone)',
    'comparison.excel.f2': 'Static charts without deep filtering',
    'comparison.excel.f3': 'Zero psychological or emotional tracking',
    'comparison.excel.f4': 'No automated edge discovery',
    'comparison.excel.f5': 'Difficult to visualize equity curves',
    'comparison.grail.title': 'TradeGrail Trading Journal',
    'comparison.grail.f1': 'One-click auto-sync with brokers',
    'comparison.grail.f2': 'Advanced multi-variable filtering',
    'comparison.grail.f3': 'Integrated psychology and error matrix',
    'comparison.grail.f4': 'AI-driven trade opportunity identification',
    'comparison.grail.f5': 'Real-time interactive equity analysis',
    'pricing.title': 'Simple, Transparent Pricing',
    'pricing.desc': 'Invest in your edge. Choose the plan that fits your trading style.',
    'pricing.currency': '$',
    'pricing.starter.price': '0',
    'pricing.pro.price': '5',
    'pricing.pro.yearly_price': '29',
    'pricing.elite.price': '12',
    'pricing.elite.yearly_price': '89',
    'pricing.pro.yearly_price': '15',
    'pricing.elite.yearly_price': '49',
    'pricing.popular': 'MOST POPULAR',
    'pricing.billing.monthly': 'Monthly',
    'pricing.billing.yearly': 'Yearly',
    'pricing.billing.save': 'Save 15%',
    'pricing.plan.starter.name': 'STARTER',
    'pricing.plan.starter.desc': 'Perfect for traders just starting out.',
    'pricing.plan.pro.name': 'PRO',
    'pricing.plan.pro.desc': 'Our most popular plan for serious traders.',
    'pricing.plan.elite.name': 'ELITE',
    'pricing.plan.elite.desc': 'Advanced features for professional & prop traders.',
    'pricing.cta.trial': 'Start 7-Day Free Trial',
    'pricing.feature.manual': 'Manual Trade Entry',
    'pricing.feature.analytics': 'Basic Performance Analytics',
    'pricing.feature.account_1': '1 Trading Account',
    'pricing.feature.charts': 'Interactive Charts',
    'pricing.feature.mobile': 'Mobile App Access',
    'pricing.feature.sync': 'Auto Broker Sync (80+ Brokers)',
    'pricing.feature.ai_edge': 'AI-Driven Edge Discovery',
    'pricing.feature.psych': 'Psychology & Error Tracking',
    'pricing.feature.unlimited': 'Unlimited Trading Accounts',
    'pricing.feature.filter': 'Advanced Multi-Variable Filter',
    'pricing.feature.support': 'Priority Email Support',
    'pricing.feature.white_label': 'White-label Performance Reports',
    'pricing.feature.api': 'Custom API Access',
    'pricing.feature.review': '1-on-1 Performance Review',
    'pricing.feature.prop_firm': 'Prop Firm Dashboard',
    'pricing.feature.manager': 'Dedicated Account Manager',
    'pricing.feature.early_access': 'Early Access to New Features',
    'pricing.feature.onboarding': 'Concierge Onboarding',
    'pricing.brokers.title': 'Seamlessly Sync With 80+ Brokers & Platforms',
    'pricing.compare.title': 'Compare Plans',
    'pricing.compare.desc': 'Detailed breakdown of features across all tiers.',
    'pricing.compare.features': 'Features',
    'pricing.compare.cat.core': 'Core Features',
    'pricing.compare.cat.analytics': 'Advanced Analytics',
    'pricing.compare.cat.reporting': 'Reporting & Support',
    'pricing.compare.cat.enterprise': 'Enterprise & API',
    'pricing.trust.security.title': 'Bank-Grade Security',
    'pricing.trust.security.desc': 'Your data is encrypted',
    'pricing.trust.globe.title': 'Global Markets',
    'pricing.trust.globe.desc': '100+ brokers supported',
    'pricing.trust.zap.title': 'Real-time Sync',
    'pricing.trust.zap.desc': 'Instant data updates',
    'pricing.trust.users.title': 'Pro Community',
    'pricing.trust.users.desc': 'Join 10,000+ traders',
    'pricing.faq.desc': 'Everything you need to know about TradeGrail.',
    'pricing.faq.q4': 'Can I switch plans later?',
    'pricing.faq.a4': 'Yes, you can upgrade or downgrade your plan at any time from your account settings.',
    'pricing.faq.q5': 'Do you offer a free trial?',
    'pricing.faq.a5': 'Yes, all plans come with a 7-day free trial. No credit card required to start.',
    'brokers.sync': 'Seamlessly sync with your favorite platforms',
    'mobile.app_store.label': 'Download on the',
    'mobile.google_play.label': 'GET IT ON',
    'pricing.starter.name': 'Starter',
    'pricing.starter.desc': 'Perfect for traders just starting out.',
    'pricing.starter.cta': 'Get Started',
    'pricing.starter.f1': 'Manual entry',
    'pricing.starter.f2': 'Basic analytics',
    'pricing.starter.f3': '1 Trading account',
    'pricing.starter.f4': 'Community access',
    'pricing.pro.name': 'Pro',
    'pricing.pro.desc': 'For serious traders looking for an edge.',
    'pricing.pro.cta': 'Upgrade to Pro',
    'pricing.pro.f1': 'Auto broker sync',
    'pricing.pro.f2': 'Advanced AI analytics',
    'pricing.pro.f3': 'Unlimited accounts',
    'pricing.pro.f4': 'Psychology matrix',
    'pricing.pro.f5': 'Priority support',
    'pricing.elite.name': 'Elite',
    'pricing.elite.desc': 'For professional and prop traders.',
    'pricing.elite.cta': 'Contact Sales',
    'pricing.elite.f1': 'Custom API access',
    'pricing.elite.f2': '1-on-1 performance review',
    'pricing.elite.f3': 'Prop firm dashboard',
    'pricing.elite.f4': 'White-label reports',
    'pricing.elite.f5': 'Dedicated manager',
    'features.bento.replay.title': 'Market Replay',
    'features.bento.replay.desc': 'Practice in real market conditions without risking real capital.',
    'features.bento.psych.title': 'Psychology Matrix',
    'features.bento.psych.desc': 'Track your emotional state and identify psychological traps leading to losses.',
    'features.bento.sync.title': 'Auto-Sync',
    'features.bento.sync.desc': 'Support for 100+ brokers with real-time data updates.',
    'testimonials.title': 'Hear from the Best',
    'testimonials.desc': 'Real traders, real results. Join the elite.',
    'testimonials.community.title': 'Join the Community of Top Traders',
    'testimonials.community.desc': 'Since 2013, thousands of traders around the world have chosen to work with us, and we continue to be the best trading journal among our competitors.',
    'testimonials.quote1': 'TradeGrail helped me find a leak in my London session trades that was costing me $2,000 a month. Paid for itself in a day.',
    'testimonials.quote2': "The Psychology Matrix is a game changer. I finally realized my FOMO was tied to specific news events. It's like having a therapist for my trading.",
    'testimonials.quote3': "I've tried TraderSync and TradeZella. TradeGrail's interface is faster and the AI insights are actually actionable. Best investment this year.",
    'testimonials.quote4': 'Love @tradegrail to help journal your trades. Simple to import trades and superb data results. My most successful trading is on Wednesday at 12 pm EST.',
    'testimonials.quote5': "Reviewing yesterday's trades on @tradegrail. The chart review is great. This was a Short (using ITM Puts) on $NVDA. Worked well.",
    'testimonials.quote6': '@tradegrail Does all the heavy lifting for you. Log them and review. Rinse, Repeat. Stop analyzing the markets all day and analyze yourself.',
    'testimonials.quote7': "Have spent some time in this chop really digging into trading journal software. After using several for a few months I'm finding @tradegrail to be the most useful for me. Also a great app. Has the best IBKR importing I've used.",
    'testimonials.quote8': 'Day traders (stocks and crypto) checkout TradeGrail. The best journal to track your data and find your edge!',
    'testimonials.quote9': 'Not only does @tradegrail have an amazing product, they are great people as well! The work they put into this product is very impressive!',
    'faq.title': 'Common Questions',
    'faq.q1': 'Which brokers do you support?',
    'faq.a1': 'We support over 100 brokers including MT4/5, NinjaTrader, Interactive Brokers, etc., via auto-sync or CSV upload.',
    'faq.q2': 'Is my data secure?',
    'faq.a2': 'Yes. We use bank-grade encryption and never share your trading data with third parties. Your edge is yours to keep.',
    'faq.q3': 'Can I cancel anytime?',
    'faq.a3': 'Absolutely. No contracts, no hidden fees. Cancel with one click from your dashboard.',
    'footer.cta.tag': 'AI TRADING JOURNAL',
    'footer.cta.title': 'Elevate Your Trading Strategy',
    'footer.cta.desc': 'What if you had a full team—an analyst, a planner, a risk manager—focused solely on your success? With TradeGrail, you do.',
    'footer.cta.button': 'Start Free Trial',
    'footer.product': 'Product',
    'footer.company': 'Company',
    'footer.support': 'Support',
    'footer.legal': 'Legal Info',
    'footer.disclaimer1': 'TradeGrail is a comprehensive suite of research, analysis, and trading tools designed to assist traders and investors in making their own decisions. We do not provide recommendations regarding specific securities to buy or sell, and we do not offer trading or investing advice. Trading carries significant risk and may not be suitable for every investor. There is a possibility of losing all or more than the initial investment.',
    'footer.disclaimer2': 'Testimonials appearing on this website may not be representative of other clients or customers and is not a guarantee of future performance or success.',
    'footer.copyright': '© 2026 TradeGrail - All Rights Reserved.',
    'footer.download.appstore': 'Download on the App Store',
    'footer.download.googleplay': 'Get it on Google Play',
    'footer.product.analytics': 'Analytics',
    'footer.product.replay': 'Market Replay Simulator',
    'footer.product.assistant': 'AI Performance Assistant',
    'footer.product.brokers': 'Supported Brokers',
    'footer.product.pricing': 'Pricing',
    'footer.product.whatsnew': "What's New",
    'footer.company.about': 'About',
    'footer.company.reviews': 'Reviews',
    'footer.company.blog': 'Blog',
    'footer.company.affiliate': 'Affiliate Program',
    'footer.support.help': 'Help Center',
    'footer.support.contact': 'Contact Us',
    'footer.support.tutorials': 'Tutorials',
    'footer.support.howto': 'How-To',
    'footer.support.glossary': 'Glossary',
    'footer.legal.terms': 'Terms and Conditions',
    'footer.legal.billing': 'Billing and Refund',
    'footer.legal.risk': 'Risk Disclosure',
    'footer.legal.privacy': 'Privacy Policy',
    'features.showcase.tag': 'FEATURE HIGHLIGHTS',
    'features.showcase.dashboard.label': 'Dashboard',
    'features.showcase.dashboard.title': 'Comprehensive Trading Overview',
    'features.showcase.dashboard.desc': 'Real-time tracking of your account performance, risk status, and AI-driven trading insights.',
    'features.showcase.analytics.label': 'Analytics',
    'features.showcase.analytics.title': 'Precision Trading Analysis',
    'features.showcase.analytics.desc': 'Deeply analyze every execution. Identify your edge through institutional-grade metrics and behavioral insights.',
    'features.showcase.journal.label': 'Journal',
    'features.showcase.journal.title': 'Interactive Trading Journal',
    'features.showcase.journal.desc': 'The most intuitive way to record and review trades. Automatically sync with your broker.',
    'features.showcase.notebook.label': 'Notebook',
    'features.showcase.notebook.title': 'Smart Trading Notes',
    'features.showcase.notebook.desc': 'Record thoughts, emotions, and market context for every trade with rich text and image support.',
    'features.showcase.reporting.label': 'Reports',
    'features.showcase.reporting.title': 'Automated Performance Reports',
    'features.showcase.reporting.desc': 'Generate professional PDF reports with one click for investors or personal review.',
    'features.showcase.backtesting.label': 'Backtesting',
    'features.showcase.backtesting.title': 'Advanced Backtesting Engine',
    'features.showcase.backtesting.desc': 'Test your strategies on historical data with institutional-grade precision.',
    'features.showcase.replay.label': 'Replay',
    'features.showcase.replay.title': 'Market Replay Simulator',
    'features.showcase.replay.desc': 'Relive market price action tick-by-tick to hone your execution and timing.',
    'features.showcase.playbook.label': 'Playbook',
    'features.showcase.playbook.title': 'Trading Playbook',
    'features.showcase.playbook.desc': 'Define your setups, rules, and risk parameters in a centralized, actionable playbook.',
    'features.showcase.cta.try': 'Try Now',
    'features.showcase.cta.docs': 'View Docs',
    'mockup.dashboard.rank': 'TRADER RANK',
    'mockup.dashboard.gold': 'Gold',
    'mockup.dashboard.next_rank': 'Progress to next rank',
    'mockup.dashboard.platinum': 'Platinum',
    'mockup.dashboard.leaderboard': 'View Global Leaderboard',
    'mockup.dashboard.risk_status': 'Risk Status: OK',
    'mockup.dashboard.safe': 'OK',
    'mockup.dashboard.risk_desc': 'You are trading within limits.',
    'mockup.dashboard.today_pl': "Today's P&L",
    'mockup.dashboard.limit': 'Limit',
    'mockup.dashboard.net_pl': 'NET P&L',
    'mockup.dashboard.win_rate': 'WIN RATE',
    'mockup.dashboard.profit_factor': 'PROFIT FACTOR',
    'mockup.dashboard.equity_curve': 'Equity Curve',
    'mockup.dashboard.initial': 'Initial',
    'mockup.dashboard.current_level': 'CURRENT LEVEL',
    'mockup.dashboard.weekly_goal': 'WEEKLY GOAL',
    'mockup.dashboard.goal_achieved': 'GOAL HIT!',
    'mockup.dashboard.current': 'CURRENT',
    'mockup.dashboard.target': 'TARGET',
    'mockup.dashboard.total_xp': 'Total Lifetime XP',
    'mockup.dashboard.view_history': 'View History',
    'mockup.dashboard.todo': 'ACTION ITEMS',
    'mockup.dashboard.discipline': 'DISCIPLINE STREAK',
    'mockup.dashboard.ai_insights': 'AI Insights',
    'mockup.dashboard.strategy_perf': 'Strategy Performance',
    'mockup.dashboard.good_morning': 'Good morning, Trader! 👋',
    'mockup.dashboard.add_trade': 'Add Trade',
    'mockup.dashboard.charts': 'Charts',
    'mockup.dashboard.playbook': 'Playbook',
    'mockup.dashboard.psychology': 'Psychology',
    'mockup.dashboard.social': 'Social Plaza',
    'mockup.dashboard.academy': 'Academy',
    'mockup.dashboard.notifications': 'Notifications',
    'mockup.dashboard.friends': 'Friends',
    'mockup.dashboard.guide': 'Guide Mode',
    'mockup.dashboard.dark_mode': 'Dark Mode',
    'mockup.dashboard.language': 'Language',
    'mockup.dashboard.journal': 'Journal',
    'mockup.dashboard.reports': 'Reports',
    'mockup.dashboard.notebook': 'Notebook',
    'mockup.dashboard.calendar': 'Calendar',
    'mockup.dashboard.all_time': 'All Time',
    'mockup.dashboard.all_accounts': 'All Accounts',
    'mockup.market.tokyo': 'Tokyo',
    'mockup.market.london': 'London',
    'mockup.market.new_york': 'New York',
    'mockup.market.closed': 'Closed',
    'mockup.market.open': 'Open',
    'mockup.analysis.tag_reviewed': 'Mark as Reviewed',
    'mockup.analysis.replay': 'Replay',
    'mockup.analysis.share': 'Share',
    'mockup.analysis.net_pl': 'Net P/L',
    'mockup.analysis.live': 'LIVE',
    'mockup.analysis.direction': 'Direction',
    'mockup.analysis.long': 'Long',
    'mockup.analysis.short': 'Short',
    'mockup.analysis.contracts': 'Contracts',
    'mockup.analysis.total_pl': 'Total P/L',
    'mockup.analysis.strategy': 'Strategy',
    'mockup.analysis.strategy_val': 'Retest',
    'mockup.analysis.mae_mfe': 'MAE / MFE',
    'mockup.analysis.rating': 'Trade Rating',
    'mockup.analysis.tp': 'Take Profit',
    'mockup.analysis.sl': 'Stop Loss',
    'mockup.analysis.autosaved': 'Autosaved',
    'mockup.analysis.annotation1': 'Check your entry and exit points',
    'mockup.analysis.annotation2': 'Enter your TP and SL levels',
    'mockup.analysis.annotation3': 'Start Journaling',
    'mockup.analysis.mistakes': 'Mistakes',
    'mockup.analysis.opportunities': 'Setups',
    'mockup.analysis.habits': 'Habits',
    'mockup.analysis.mistake1': 'Late Entry',
    'mockup.analysis.mistake2': 'Early Exit',
    'mockup.analysis.opp1': 'Gap Push',
    'mockup.analysis.habit1': 'Good Sleep',
    'mockup.analysis.running_pl': 'Running P&L',
    'mockup.analysis.note_placeholder': '"Price hit liquidity sweep zone and showed strong rejection. Entered on 15m retest, high confidence..."',
    'mockup.journal.month': 'February 2026',
    'mockup.journal.today': 'Today',
    'mockup.journal.total_pl': 'Total P/L',
    'mockup.journal.total_trades': 'Total Trades',
    'mockup.journal.trades_count': 'Trades',
    'mockup.journal.trades': 'Trades',
    'mockup.journal.all_time': 'All Time',
    'mockup.journal.sun': 'Sun',
    'mockup.journal.mon': 'Mon',
    'mockup.journal.tue': 'Tue',
    'mockup.journal.wed': 'Wed',
    'mockup.journal.thu': 'Thu',
    'mockup.journal.fri': 'Fri',
    'mockup.journal.sat': 'Sat',
    'mockup.journal.february': 'February',
    'mockup.journal.annotation1': 'Visualize your daily performance',
    'mockup.journal.annotation2': 'Track your habits and mistakes',
    'mockup.notebook.new_folder': 'New Folder',
    'mockup.notebook.new_note': 'New Note',
    'mockup.notebook.folders': 'Folders',
    'mockup.notebook.all_notes': 'All Notes',
    'mockup.notebook.folder1': 'Trading Notes',
    'mockup.notebook.folder2': 'Quarterly Goals',
    'mockup.notebook.folder3': 'Action Plans',
    'mockup.notebook.trading_notes': 'Trading Notes',
    'mockup.notebook.quarterly_goals': 'Quarterly Goals',
    'mockup.notebook.action_plans': 'Action Plans',
    'mockup.notebook.daily_journal': 'Daily Journal',
    'mockup.notebook.weekly_review': 'Weekly Review',
    'mockup.notebook.monthly_summary': 'Monthly Summary',
    'mockup.notebook.daily_logs': 'Daily Logs',
    'mockup.notebook.weekly_reviews': 'Weekly Reviews',
    'mockup.notebook.monthly_summaries': 'Monthly Summaries',
    'mockup.notebook.chart_analysis': 'Chart Analysis',
    'mockup.notebook.templates': 'Templates',
    'mockup.notebook.tags': 'Tags',
    'mockup.notebook.tag_high_win': 'High Win Rate',
    'mockup.notebook.tag_fomo': 'FOMO',
    'mockup.notebook.trash': 'Trash',
    'mockup.notebook.search': 'Search Notes (F6)',
    'mockup.notebook.search_placeholder': 'Search Notes',
    'mockup.notebook.select_all': 'Select All',
    'mockup.notebook.created_at': 'Created at',
    'mockup.notebook.updated_at': 'Updated at',
    'mockup.notebook.autosave': 'Autosave',
    'mockup.notebook.link_trades': 'Link Trades',
    'mockup.notebook.add_tag': 'Add Tag',
    'mockup.notebook.save_template': 'Save Template',
    'mockup.notebook.save_as_template': 'Save as Template',
    'mockup.notebook.body': 'Body',
    'mockup.notebook.h1': 'Heading 1',
    'mockup.notebook.h2': 'Heading 2',
    'mockup.notebook.key_insight': 'Key Insight',
    'mockup.notebook.insight_desc': 'Waiting for confirmation is much more robust than blind prediction. Order flow shift after liquidity sweep is the best entry time.',
    'mockup.notebook.emotional_state': 'Emotional state: Calm, focused. No FOMO after previous losses. Strictly followed risk parameters.',
    'mockup.notebook.ai_insight': 'AI Strategy Insight',
    'mockup.notebook.ai_suggest': 'Suggest adding "Liquidity Sweep"',
    'mockup.notebook.ai_suggestion': 'Suggest adding "Liquidity Sweep"',
    'mockup.notebook.annotation1': 'Immersive Rich Text Editor',
    'mockup.notebook.annotation2': 'Link your live trades with one click',
    'mockup.notebook.note1_title': 'Trade Review',
    'mockup.notebook.note2_title': '2026-03-01 Review',
    'mockup.notebook.note3_title': 'Quarterly Goal Setting',
    'mockup.notebook.note4_title': 'Breakout Strategy Optimization',
    'mockup.notebook.note5_title': 'Psychology Tracking',
    'mockup.notebook.note_content1': 'Observed a perfect liquidity sweep pattern on the 15m chart of 1000SATS/USDT today.',
    'mockup.notebook.note_content2': 'Price hit previous swing highs and quickly rejected, forming a strong bearish signal. Entered short on 50% fib retest.',
    'mockup.notebook.content_p1': 'Observed a perfect liquidity sweep pattern on the 15m chart of 1000SATS/USDT today.',
    'mockup.notebook.content_p2': 'Price hit previous swing highs and quickly rejected, forming a strong bearish signal. Entered short on 50% fib retest.',
    'mockup.notebook.content_insight': 'Waiting for confirmation is much more robust than blind prediction. Order flow shift after liquidity sweep is the best entry time.',
    'mockup.notebook.content_p3': 'Emotional state: Calm, focused. No FOMO after previous losses. Strictly followed risk parameters.',
    'mockup.reports.title': 'Performance Reports',
    'mockup.reports.filter': 'Filter',
    'mockup.reports.generate': 'Generate Report',
    'mockup.reports.export': 'Export PDF',
    'mockup.reports.stats_title': 'Statistics',
    'mockup.reports.best_month': 'Best Month',
    'mockup.reports.best_month_sub': 'Best historical performance',
    'mockup.reports.best_month_desc': 'Best historical performance',
    'mockup.reports.worst_month': 'Worst Month',
    'mockup.reports.worst_month_sub': 'Max drawdown period',
    'mockup.reports.worst_month_desc': 'Max drawdown period',
    'mockup.reports.avg_month': 'Avg. Monthly P/L',
    'mockup.reports.avg_monthly': 'Avg. Monthly P/L',
    'mockup.reports.avg_month_sub': 'Average baseline level',
    'mockup.reports.avg_monthly_desc': 'Average baseline level',
    'mockup.reports.stats_data': 'Statistics (All Dates)',
    'mockup.reports.detailed_stats': 'Statistics',
    'mockup.reports.total_pl': 'Total P/L',
    'mockup.reports.avg_hold_loss': 'Avg. Hold Time (Loss)',
    'mockup.reports.avg_hold_even': 'Avg. Hold Time (Even)',
    'mockup.reports.avg_vol': 'Avg. Daily Volume',
    'mockup.reports.avg_daily_vol': 'Avg. Daily Volume',
    'mockup.reports.avg_win': 'Average Win',
    'mockup.reports.avg_trade_pl': 'Avg. Trade P/L',
    'mockup.reports.avg_pl_per_trade': 'Avg. Trade P/L',
    'mockup.reports.avg_loss': 'Average Loss',
    'mockup.reports.pf': 'Profit Factor (PF)',
    'mockup.reports.profit_factor': 'Profit Factor (PF)',
    'mockup.reports.total_trades': 'Total Trades',
    'mockup.reports.open_trades': 'Open Trades',
    'mockup.reports.open_positions': 'Open Trades',
    'mockup.reports.win_trades': 'Winning Trades',
    'mockup.reports.winning_trades': 'Winning Trades',
    'mockup.reports.total_days': 'Total Trading Days',
    'mockup.reports.loss_trades': 'Losing Trades',
    'mockup.reports.losing_trades': 'Losing Trades',
    'mockup.reports.win_days': 'Winning Days',
    'mockup.reports.winning_days': 'Winning Days',
    'mockup.reports.even_trades': 'Even Trades',
    'mockup.reports.loss_days': 'Losing Days',
    'mockup.reports.losing_days': 'Losing Days',
    'mockup.reports.max_win_streak': 'Max Win Streak',
    'mockup.reports.even_days': 'Even Days',
    'mockup.reports.max_loss_streak': 'Max Loss Streak',
    'mockup.reports.recorded_days': 'Recorded Days',
    'mockup.reports.commissions': 'Total Commissions',
    'mockup.reports.total_fees': 'Total Commissions',
    'mockup.reports.max_win_days': 'Max Green Days Streak',
    'mockup.reports.max_green_streak': 'Max Green Days Streak',
    'mockup.reports.swap': 'Swap Fees',
    'mockup.reports.overnight_fees': 'Swap Fees',
    'mockup.reports.max_loss_days': 'Max Red Days Streak',
    'mockup.reports.max_red_streak': 'Max Red Days Streak',
    'mockup.reports.max_win': 'Max Single Win',
    'mockup.reports.avg_daily_pl': 'Avg. Daily P/L',
    'mockup.reports.max_loss': 'Max Single Loss',
    'mockup.reports.max_daily_loss': 'Max Daily Loss',
    'mockup.showcase.integrations': '80+ Trading Platform Integrations',
    'mockup.showcase.see_all': 'See All Integrations',
    'mockup.showcase.import': 'Import trades',
    'mockup.showcase.dashboard': 'Dashboard',
    'mockup.showcase.edit_layout': 'Edit layout',
    'mockup.showcase.recent_shared': 'Your recent shared trades',
    'mockup.showcase.largest_gain': 'Largest Gain',
    'mockup.showcase.total_gain_loss': 'Total Gain Loss',
    'mockup.showcase.k_ratio': 'K Ratio',
    'mockup.showcase.hourly': 'Hourly',
    'mockup.showcase.search': 'Search',
    'mockup.showcase.plan_gold': 'Plan: Gold',
    'mockup.showcase.days_30': '30 days',
    'mockup.showcase.days_60': '60 days',
    'mockup.showcase.days_90': '90 days',
    'mockup.showcase.custom': 'Custom',
    'mockup.showcase.today': 'Today',
    'mockup.showcase.may_2024': 'May, 2024',
    'mockup.showcase.community': 'Community',
    'mockup.showcase.new_trade': 'New trade',
    'mockup.interactive.system_title': 'Real-time Equity Analysis System',
    'mockup.interactive.initial_capital': 'INITIAL CAPITAL',
    'mockup.interactive.strategy_analysis': 'Multi-dimensional Strategy Win Rate Analysis',
    'mockup.interactive.live_feed': 'LIVE DATA FEED',
    'mockup.interactive.ai_insights': 'AI Intelligent Decision Insights',
    'mockup.interactive.insight1': 'Core Error: Execution Hesitation',
    'mockup.interactive.insight2': 'High Win Rate Setup: Fib Retracement (67%)',
    'mockup.interactive.insight3': 'Optimization Tip: Strictly enforce entry standards',
    'mockup.interactive.strategy1': 'Fib Retracement',
    'mockup.interactive.strategy2': 'Support Bounce',
    'mockup.interactive.strategy3': 'Breakout Strategy',
    'mockup.interactive.strategy4': 'News Event',
    'mockup.interactive.strategy5': 'Gap Fill',
    'mockup.interactive.strategy6': 'Trend Pullback',
    'mockup.interactive.strategy7': 'Liquidity Sweep',
    'mockup.interactive.strategy8': 'Trend Following',
    'mockup.reports.equity_curve_title': 'Daily Cumulative Net P/L (Equity Curve)',
    'mockup.reports.daily_pl_title': 'Daily Net P/L',
    'mockup.reports.hours': 'h',
    'mockup.reports.minutes': 'm',
    'playbook.title': 'Trading Playbook',
    'playbook.search': 'Search strategy... (F6)',
    'playbook.create': 'Create New Strategy',
    'playbook.learn_more': 'Learn more',
    'playbook.trades': 'trades',
    'playbook.private': 'Private',
    'playbook.public': 'Public',
    'playbook.win_rate': 'Win Rate',
    'playbook.net_pl': 'Net P&L',
    'playbook.view_details': 'View Details',
    'playbook.sort': 'Sort:',
    'playbook.all_categories': 'All Categories',
    'playbook.long_only': 'Long Only',
    'playbook.short_only': 'Short Only',
    'playbook.define_edge': 'Define your edge',
    'playbook.strat.breakout.title': 'Breakout',
    'playbook.strat.breakout.desc': 'Taking trades when price breaks a key resistance level with volume confirmation.',
    'playbook.strat.gap.title': 'Gap and Go',
    'playbook.strat.gap.desc': 'Day trading strategy for stocks gapping up pre-market.',
    'playbook.strat.sweep.title': 'Liquidity Sweep',
    'playbook.strat.sweep.desc': 'Reversal setup after stops are triggered above/below a swing point.',
    'playbook.strat.bounce.title': 'Support Bounce',
    'playbook.strat.bounce.desc': 'Buying at a proven demand zone or support level.',
    'playbook.strat.pullback.title': 'Trend Pullback',
    'playbook.strat.pullback.desc': 'Entering in the direction of the trend after a retracement to equilibrium.',
    'auth.login.title': 'Welcome Back to TradeGrail',
    'auth.login.desc': 'Continue your path to trading with systematic confidence.',
    'auth.login.email_label': 'Email or Username',
    'auth.login.password_label': 'Password',
    'auth.login.forgot_password': 'Forgot Password?',
    'auth.login.submit': 'Sign In',
    'auth.login.no_account': "Don't have an account?",
    'auth.login.create_account': 'Create Account',
    'auth.signup.title': 'Activate Your Personal AI Analyst',
    'auth.signup.desc': 'Your path to trading with systematic confidence starts now.',
    'auth.signup.first_name_label': 'First Name',
    'auth.signup.email_label': 'Email',
    'auth.signup.username_label': 'Username',
    'auth.signup.password_label': 'Password',
    'auth.signup.agree_terms': 'I agree to the',
    'auth.signup.terms_link': 'Terms and Conditions',
    'auth.signup.submit': 'Sign Up',
    'auth.signup.has_account': 'Already a user?',
    'auth.signup.sign_in': 'Sign In',
    'auth.signup.error_terms': 'Please agree to the Terms and Conditions',
    'auth.tags.analyze': 'Analyze',
    'auth.tags.backtest': 'Backtest',
    'auth.tags.ai_analyst': 'AI Analyst',
    'auth.google_button': 'Continue with Google',
    'auth.or_divider': 'OR',
    'auth.login.email_placeholder': 'Enter your email',
    'auth.login.password_placeholder': 'Enter your password',
    'auth.login.error_failed': 'Login failed, please check your email and password',
    'auth.login.error_google': 'Google login failed',
    'auth.signup.first_name_placeholder': 'Enter your first name',
    'auth.signup.email_placeholder': 'Enter your email',
    'auth.signup.username_placeholder': 'Enter your username',
    'auth.signup.password_placeholder': 'Create a password',
    'auth.signup.confirm_password_label': 'Confirm Password',
    'auth.signup.confirm_password_placeholder': 'Confirm your password',
    'auth.signup.error_password_mismatch': 'Passwords do not match',
    'auth.signup.error_failed': 'Registration failed, please try again',
    'auth.signup.error_google': 'Google registration failed',
    'auth.confirm.title': 'Check Your Email',
    'auth.confirm.desc': 'We sent a confirmation link to',
    'auth.confirm.desc2': 'Click the link to activate your account.',
    'auth.confirm.spam': "Didn't receive it? Check your spam folder.",
    'auth.confirm.resend': 'Resend confirmation email',
    'auth.confirm.resent': 'Email resent successfully!',
    'auth.confirm.go_login': 'Already confirmed? Sign in',
    'nav.features.journal.title': 'AI Smart Dashboard',
    'nav.features.journal.desc': 'Analyze trading data in real-time with AI-driven market insights.',
    'nav.features.backtest.title': 'Backtesting Engine',
    'nav.features.backtest.desc': 'Validate your trading strategies with massive historical market data.',
    'nav.features.spaces.title': 'Strategy Playbook',
    'nav.features.spaces.desc': 'Build and manage your trading rules for disciplined execution.',
    'nav.features.prop.title': 'AI Market Analyst',
    'nav.features.prop.desc': 'Powered by Gemini 3.1 Pro for professional real-time analysis.',
    'nav.features.replay.title': 'Market Pulse',
    'nav.features.replay.desc': 'Monitor global market trends and sentiment in real-time.',
    'nav.features.university.title': 'TradeGrail Academy',
    'nav.features.university.desc': 'Master systematic trading logic from the ground up.',
    'nav.features.ai.title': 'Prop Firm Sync',
    'nav.features.ai.desc': 'Manage your prop accounts and track progress in one place.',
    'nav.features.coming_soon': 'COMING SOON',
    'pricing.crypto.title': 'Cryptocurrency Payment',
    'pricing.crypto.desc': 'We now support payments via major cryptocurrencies including BTC, ETH, and USDT.',
    'checkout.title': 'Checkout',
    'checkout.order_summary': 'Order Summary',
    'checkout.payment_details': 'Payment Details',
    'checkout.email': 'Email Address',
    'checkout.card_number': 'Card Number',
    'checkout.expiry': 'Expiry Date',
    'checkout.cvc': 'CVC',
    'checkout.pay_now': 'Pay Now',
    'checkout.crypto_option': 'Pay with Cryptocurrency',
    'checkout.secure_payment': 'Secure Payment Guaranteed',
    'checkout.total': 'Total',
    'checkout.back': 'Back to Pricing',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('zh');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && (savedLang === 'zh' || savedLang === 'en')) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
