import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    'nav.features': '产品',
    'nav.products': '产品',
    'nav.solutions': '解决方案',
    'nav.pricing': '价格',
    'nav.resources': '资源',
    'nav.build_public': '公开构建',
    'nav.login': '登录',
    'nav.logout': '退出登录',
    'nav.signup': '立即开始',
    'nav.solutions.crypto': '加密货币交易者',
    'nav.solutions.crypto.desc': '加密交易复盘流程正在验证中，暂不宣传交易所同步',
    'nav.solutions.stocks': '股票 / 期货交易者',
    'nav.solutions.stocks.desc': '港股、A 股、期货，CSV 导入或手动记录均可',
    'nav.solutions.prop': '自营交易者',
    'nav.solutions.prop.desc': '自营账户流程仍在规划中，暂不作为当前承诺',
    'nav.resources.academy': 'TradeGrail 学院',
    'nav.resources.academy.desc': '系统化交易课程，从入门到进阶',
    'nav.resources.tutorials': '使用教程',
    'nav.resources.tutorials.desc': '快速上手指南与功能详解',
    'nav.resources.faq': '常见问题',
    'nav.resources.faq.desc': '解答你最关心的问题',
    'nav.view_all': '查看全部功能',
    'hero.badge': '公开构建中的交易复盘 SaaS',
    'hero.title': '把每笔交易变成',
    'hero.title.accent': '可复盘的决策记录。',
    'hero.desc': 'TradeGrail 正在从 AI 编程原型走向专业交易复盘 SaaS。当前重点是交易日志、执行复盘、风险纪律追踪和谨慎的 AI 辅助总结。',
    'hero.cta': '加入早期体验',
    'hero.demo': '进入登录',
    'hero.stats.roi': '月均投资回报率',
    'hero.stats.profit_factor': '获利因子',
    'hero.stats.traders': '活跃交易者',
    'hero.stats.volume': '已分析交易量',
    'hero.stats.winrate': '复盘质量',
    'features.tag': '当前构建重点',
    'features.title': '先把复盘流程',
    'features.title.accent': '做扎实。',
    'features.desc': 'TradeGrail 当前优先完善交易记录、标签、风险纪律、复盘分析和 AI 辅助总结。未稳定的功能不会作为宣传承诺。',
    'features.bento.title': '为真实复盘流程而建',
    'features.bento.desc': '我们公开打磨产品边界、文案和功能，把原型逐步变成可以被交易者信任的工具。',
    'features.bento.ai.title': 'AI 辅助复盘摘要',
    'features.bento.ai.desc': 'AI 用于帮助整理交易记录、总结行为模式和提出复盘问题，不提供交易建议，也不承诺收益提升。',
    'features.bento.trust': '当前阶段',
    'features.bento.trust.desc': '公开构建、早期验证、谨慎开放',
    'features.bento.psych.tag': '心理分析',
    'features.bento.security.title': '信任优先',
    'features.bento.security.desc': '我们正在清理旧认证、支付和数据边界，安全表述会以实际验证为准。',
    'features.bento.global.title': '范围清晰',
    'features.bento.global.desc': '当前优先支持手动记录和可验证的数据导入流程，不提前承诺大规模券商同步。',
    'build.status.prototype': '原型',
    'build.status.beta': 'Beta',
    'build.status.audit': '审计',
    'build.status.public': '公开',
    'build.strip.tag': 'Build in Public',
    'build.strip.title': '我们会公开记录 TradeGrail 从 AI 原型走向专业 SaaS 的过程。',
    'build.strip.desc': '公开内容会包括产品边界、复盘流程、设计修改、技术风险清理和早期用户反馈；不会伪造用户评价、媒体背书或成熟度。',
    'mockup.title': '可视化您的',
    'mockup.title.accent': '成功之路。',
    'mockup.desc': '我们的仪表盘不仅美观，而且功能强大。每一个像素的设计都是为了帮助您发现模式并消除错误。',
    'mockup.feature1': '实时权益曲线追踪',
    'mockup.feature2': '自动错误标记',
    'mockup.feature3': '可定制的报告组件',
    'mobile.tag': 'Web 优先',
    'mobile.title': '先把核心 Web 复盘',
    'mobile.title.accent': '体验做稳。',
    'mobile.desc': '当前重点是让桌面和移动浏览器里的交易记录、标签、复盘和分析流程足够清晰。原生 App 不作为当前公开承诺。',
    'mobile.web_cta': '体验 Web 版本',
    'mobile.app_status': '原生 App 暂未发布',
    'comparison.title': '停止使用电子表格。',
    'comparison.desc': '表格能记录结果，但很难稳定记录决策、风险、纪律和复盘过程。',
    'comparison.excel.title': '传统电子表格',
    'comparison.excel.f1': '手动数据录入（缓慢且易错）',
    'comparison.excel.f2': '缺乏深度过滤的静态图表',
    'comparison.excel.f3': '零心理或情绪追踪',
    'comparison.excel.f4': '很难沉淀每次犯错和遵守规则的原因',
    'comparison.excel.f5': '难以可视化权益曲线',
    'comparison.grail.title': 'TradeGrail 交易日志',
    'comparison.grail.f1': '手动记录和可验证导入优先',
    'comparison.grail.f2': '高级多变量过滤',
    'comparison.grail.f3': '集成的心理与错误矩阵',
    'comparison.grail.f4': 'AI 辅助整理复盘摘要和行为模式',
    'comparison.grail.f5': '逐步完善的权益和表现分析',
    'pricing.title': '早期 Beta 价格',
    'pricing.desc': 'TradeGrail 仍处于从原型走向专业 SaaS 的阶段。价格和功能会保持透明，未验证的能力不会包装成正式承诺。',
    'pricing.currency': '¥',
    'pricing.starter.price': '0',
    'pricing.pro.price': '早期价待定',
    'pricing.pro.yearly_price': '早期价待定',
    'pricing.elite.price': '规划中',
    'pricing.elite.yearly_price': '规划中',
    'pricing.popular': '建议体验',
    'pricing.billing.monthly': '按月付费',
    'pricing.billing.yearly': '按年付费',
    'pricing.billing.save': '立省 15%',
    'pricing.plan.starter.name': '入门版 (STARTER)',
    'pricing.plan.starter.desc': '适合先体验手动记录和基础复盘流程。',
    'pricing.plan.pro.name': 'Beta 共建版',
    'pricing.plan.pro.desc': '适合愿意给反馈、帮助打磨复盘流程的早期交易者。',
    'pricing.plan.elite.name': '未来版本',
    'pricing.plan.elite.desc': '团队、API、白标和自营交易流程仍在规划中。',
    'pricing.cta.trial': '申请早期体验',
    'pricing.feature.manual': '手动录入交易',
    'pricing.feature.analytics': '基础表现分析',
    'pricing.feature.account_1': '1 个交易账户',
    'pricing.feature.charts': '交互式图表',
    'pricing.feature.mobile': '移动浏览器访问',
    'pricing.feature.sync': '导入/同步能力待验证',
    'pricing.feature.ai_edge': 'AI 辅助复盘摘要',
    'pricing.feature.psych': '心理与错误追踪',
    'pricing.feature.unlimited': '无限交易账户',
    'pricing.feature.filter': '高级多变量过滤',
    'pricing.feature.support': '优先邮件支持',
    'pricing.feature.white_label': '白标报告规划中',
    'pricing.feature.api': 'API 规划中',
    'pricing.feature.review': '人工复盘服务待验证',
    'pricing.feature.prop_firm': '自营交易流程规划中',
    'pricing.feature.manager': '早期反馈沟通',
    'pricing.feature.early_access': '新功能优先体验',
    'pricing.feature.onboarding': '专属入驻指导',
    'pricing.brokers.title': '导入与同步能力会逐项验证后再公开承诺',
    'pricing.compare.title': '方案对比',
    'pricing.compare.desc': '各层级功能的详细细分。',
    'pricing.compare.features': '功能',
    'pricing.compare.cat.core': '核心功能',
    'pricing.compare.cat.analytics': '高级分析',
    'pricing.compare.cat.reporting': '报告与支持',
    'pricing.compare.cat.enterprise': '企业与 API',
    'pricing.trust.security.title': '安全审计中',
    'pricing.trust.security.desc': '以实际验证为准',
    'pricing.trust.globe.title': '范围透明',
    'pricing.trust.globe.desc': '不夸大支持范围',
    'pricing.trust.zap.title': '逐步上线',
    'pricing.trust.zap.desc': '稳定优先',
    'pricing.trust.users.title': '早期共建',
    'pricing.trust.users.desc': '真实反馈优先',
    'pricing.faq.desc': '当前阶段的真实说明。',
    'pricing.faq.q4': '以后可以更换方案吗？',
    'pricing.faq.a4': '可以。正式收费和套餐调整会在支付、权限和退款流程验证后再明确。',
    'pricing.faq.q5': '现在是正式商业发布吗？',
    'pricing.faq.a5': '不是。当前是 Build in Public 和早期 Beta 阶段，重点是验证真实复盘流程和信任基础。',
    'pricing.beta.badge': '早期 Beta',
    'pricing.beta.title': '为什么不把价格包装成成熟 SaaS？',
    'pricing.beta.desc': '因为 TradeGrail 还在清理认证、支付、数据边界和产品范围。我们会先真实说明当前能力，邀请少量早期用户共建，再逐步开放正式付费。',
    'pricing.future.imports': '更多导入方式规划中',
    'pricing.future.reports': '专业报告规划中',
    'pricing.future.teams': '团队功能规划中',
    'brokers.sync': '与您喜爱的平台无缝同步',
    'mobile.app_store.label': '原生 App 暂未发布',
    'mobile.google_play.label': '移动浏览器优先',
    'pricing.starter.name': '入门版',
    'pricing.starter.desc': '适合正在起步的新手交易者。',
    'pricing.starter.cta': '立即开始',
    'pricing.starter.f1': '手动录入交易',
    'pricing.starter.f2': '基础分析',
    'pricing.starter.f3': '1 个交易账户',
    'pricing.starter.f4': '社区访问',
    'pricing.pro.name': '专业版',
    'pricing.pro.desc': '适合正在进阶的职业交易者。',
    'pricing.pro.cta': '升级专业版',
    'pricing.pro.f1': '导入流程待验证',
    'pricing.pro.f2': 'AI 辅助复盘',
    'pricing.pro.f3': '无限账户',
    'pricing.pro.f4': '心理矩阵',
    'pricing.pro.f5': '早期反馈沟通',
    'pricing.elite.name': '精英版',
    'pricing.elite.desc': '适合专业及自营交易员。',
    'pricing.elite.cta': '联系销售',
    'pricing.elite.f1': 'API 规划中',
    'pricing.elite.f2': '人工复盘待验证',
    'pricing.elite.f3': '自营交易流程规划中',
    'pricing.elite.f4': '报告能力规划中',
    'pricing.elite.f5': '团队流程规划中',
    'features.bento.replay.title': '市场复盘',
    'features.bento.replay.desc': '在真实的市场条件下练习，无需真金白银。',
    'features.bento.psych.title': '心理矩阵',
    'features.bento.psych.desc': '追踪您的情绪状态，识别导致亏损的心理陷阱。',
    'features.bento.sync.title': '自动同步',
    'features.bento.sync.desc': '同步能力会在真实验证后逐步开放。',
    'testimonials.title': '当前不使用虚假评价',
    'testimonials.desc': 'TradeGrail 还没有足够真实、可公开授权的客户评价。因此这里改为说明我们正在公开构建什么。',
    'testimonials.note.prototype.title': '从原型到产品',
    'testimonials.note.prototype.desc': '我们会公开展示从 AI 编程原型走向可上线 SaaS 的修改过程。',
    'testimonials.note.trust.title': '先清理信任风险',
    'testimonials.note.trust.desc': '旧认证、支付、诊断接口、密钥命名和数据边界会优先处理。',
    'testimonials.note.scope.title': '不提前承诺',
    'testimonials.note.scope.desc': '券商同步、API、移动 App、白标和机构功能会验证后再宣传。',
    'testimonials.note.beta.title': '邀请早期共建',
    'testimonials.note.beta.desc': '早期用户反馈会用于打磨交易记录、复盘和 AI 摘要流程。',
    'testimonials.community.title': '一起把复盘工具做真实',
    'testimonials.community.desc': '我们欢迎早期交易者试用并指出哪些复盘流程真正有用，哪些只是看起来很酷。',
    'testimonials.quote1': '早期反馈收集中。',
    'testimonials.quote2': '早期反馈收集中。',
    'testimonials.quote3': '早期反馈收集中。',
    'testimonials.quote4': '早期反馈收集中。',
    'testimonials.quote5': '早期反馈收集中。',
    'testimonials.quote6': '早期反馈收集中。',
    'testimonials.quote7': '早期反馈收集中。',
    'testimonials.quote8': '早期反馈收集中。',
    'testimonials.quote9': '早期反馈收集中。',
    'faq.title': '常见问题',
    'faq.q1': '你们支持哪些券商？',
    'faq.a1': '当前不宣传大规模券商自动同步。我们会优先打磨手动记录、CSV/导入流程，并在每个集成稳定后再公开说明。',
    'faq.q2': '我的数据安全吗？',
    'faq.a2': '交易数据是核心信任资产。当前我们正在清理认证、支付和数据边界；具体安全声明会以 CTO 验证后的内容为准。',
    'faq.q3': '我可以随时取消订阅吗？',
    'faq.a3': '早期 Beta 阶段会先保持低门槛体验。正式订阅和取消流程会在支付系统验证后公开说明。',
    'footer.cta.tag': 'Build in Public',
    'footer.cta.title': '参与 TradeGrail 的早期共建',
    'footer.cta.desc': '如果你正在用表格、截图或零散笔记复盘交易，欢迎试用早期版本，并帮助我们把真实交易复盘流程做扎实。',
    'footer.cta.button': '加入早期体验',
    'footer.product': '产品',
    'footer.company': '公司',
    'footer.support': '支持',
    'footer.legal': '法律信息',
    'footer.disclaimer1': 'TradeGrail 是一套全面的研究、分析和交易工具，旨在协助交易者和投资者做出自己的决策。我们不提供有关购买或出售特定证券的建议，也不提供交易或投资建议。交易具有重大风险，可能并不适合每位投资者。存在损失全部或超过初始投资的可能性。',
    'footer.disclaimer2': 'TradeGrail 当前处于早期 Beta 和公开构建阶段。网站不使用虚假评价、假头像或未经验证的媒体背书。',
    'footer.copyright': '© 2026 TradeGrail - 保留所有权利。',
    'footer.download.appstore': '原生 App 暂未发布',
    'footer.download.googleplay': '移动浏览器优先',
    'footer.product.analytics': '分析',
    'footer.product.replay': '复盘流程',
    'footer.product.assistant': 'AI 复盘助手',
    'footer.product.brokers': '导入计划',
    'footer.product.pricing': '价格',
    'footer.product.whatsnew': '更新日志',
    'footer.company.about': '关于我们',
    'footer.company.reviews': '早期反馈',
    'footer.company.blog': '公开构建',
    'footer.company.affiliate': '合作计划暂未开放',
    'footer.support.help': '帮助中心',
    'footer.support.contact': '联系我们',
    'footer.support.tutorials': '教程规划中',
    'footer.support.howto': '操作指南规划中',
    'footer.support.glossary': '词汇表规划中',
    'footer.legal.terms': '条款和条件',
    'footer.legal.billing': '账单和退款',
    'footer.legal.risk': '风险披露',
    'footer.legal.privacy': '隐私政策',
    'footer.beta_note': '早期 Beta：原生 App 暂未发布，部分能力仍在验证。',
    'features.showcase.tag': '功能亮点',
    'features.showcase.dashboard.label': '仪表盘',
    'features.showcase.dashboard.title': '全方位交易概览',
    'features.showcase.dashboard.desc': '追踪账户表现、风险状态和 AI 辅助复盘摘要。',
    'features.showcase.analytics.label': '分析',
    'features.showcase.analytics.title': '精准交易分析',
    'features.showcase.analytics.desc': '复盘每一次执行，观察策略、风险和行为模式。',
    'features.showcase.journal.label': '日志',
    'features.showcase.journal.title': '交互式交易日志',
    'features.showcase.journal.desc': '记录和复盘交易的工作区。导入与同步能力会逐项验证后开放。',
    'features.showcase.notebook.label': '笔记本',
    'features.showcase.notebook.title': '智能交易笔记',
    'features.showcase.notebook.desc': '通过富文本和图片支持，记录每笔交易的想法、情绪和市场背景。',
    'features.showcase.reporting.label': '报告',
    'features.showcase.reporting.title': '自动化表现报告',
    'features.showcase.reporting.desc': '报告能力仍在打磨中，优先服务个人复盘而非对外募资展示。',
    'features.showcase.backtesting.label': '回测',
    'features.showcase.backtesting.title': '复盘与回测规划',
    'features.showcase.backtesting.desc': '回测能力仍在规划中，当前不作为正式承诺。',
    'features.showcase.replay.label': '复盘',
    'features.showcase.replay.title': '市场回放模拟器',
    'features.showcase.replay.desc': '市场回放仍在规划中，当前先完善交易后复盘流程。',
    'features.showcase.playbook.label': '策略库',
    'features.showcase.playbook.title': '交易策略库',
    'features.showcase.playbook.desc': '在集中的、可执行的策略库中定义您的交易机会、规则和风险参数。',
    'features.showcase.cta.try': '立即体验',
    'features.showcase.cta.docs': '查看文档',
    'mockup.dashboard.rank': '交易员段位',
    'mockup.dashboard.gold': '黄金',
    'mockup.dashboard.next_rank': '距离下一段位',
    'mockup.dashboard.platinum': '铂金',
    'mockup.dashboard.leaderboard': '查看全球排行榜',
    'mockup.dashboard.risk_status': '风控状态: 正常',
    'mockup.dashboard.safe': '正常',
    'mockup.dashboard.risk_desc': '您在允许的亏损范围内。',
    'mockup.dashboard.today_pl': '今日盈亏',
    'mockup.dashboard.limit': '限制',
    'mockup.dashboard.net_pl': '净盈亏',
    'mockup.dashboard.win_rate': '胜率',
    'mockup.dashboard.profit_factor': '获利因子',
    'mockup.dashboard.equity_curve': '资金曲线',
    'mockup.dashboard.initial': '初始',
    'mockup.dashboard.current_level': '当前等级',
    'mockup.dashboard.weekly_goal': '本周目标',
    'mockup.dashboard.goal_achieved': '达成目标！',
    'mockup.dashboard.current': '当前',
    'mockup.dashboard.target': '目标',
    'mockup.dashboard.total_xp': '累计获得 XP',
    'mockup.dashboard.view_history': '查看历史',
    'mockup.dashboard.todo': '行动清单',
    'mockup.dashboard.discipline': '纪律追踪',
    'mockup.dashboard.ai_insights': 'AI 洞察',
    'mockup.dashboard.strategy_perf': '策略表现',
    'mockup.dashboard.good_morning': '早安, 交易员! 👋',
    'mockup.dashboard.add_trade': '添加交易',
    'mockup.dashboard.charts': '图表',
    'mockup.dashboard.playbook': '策略库',
    'mockup.dashboard.psychology': '心理矩阵',
    'mockup.dashboard.social': '社交广场',
    'mockup.dashboard.academy': '交易学院',
    'mockup.dashboard.notifications': '通知',
    'mockup.dashboard.friends': '好友',
    'mockup.dashboard.guide': '新手引导',
    'mockup.dashboard.dark_mode': '深色模式',
    'mockup.dashboard.language': '语言',
    'mockup.dashboard.journal': '交易日志',
    'mockup.dashboard.reports': '表现报告',
    'mockup.dashboard.notebook': '交易笔记',
    'mockup.dashboard.calendar': '交易日历',
    'mockup.dashboard.all_time': '所有时间',
    'mockup.dashboard.all_accounts': '所有账户',
    'mockup.market.tokyo': '东京',
    'mockup.market.london': '伦敦',
    'mockup.market.new_york': '纽约',
    'mockup.market.closed': '休市',
    'mockup.market.open': '开市',
    'mockup.analysis.tag_reviewed': '标记为已复盘',
    'mockup.analysis.replay': '回放',
    'mockup.analysis.share': '分享',
    'mockup.analysis.net_pl': '净盈亏',
    'mockup.analysis.live': '实时',
    'mockup.analysis.direction': '方向',
    'mockup.analysis.long': '做多',
    'mockup.analysis.short': '做空',
    'mockup.analysis.contracts': '合约数量',
    'mockup.analysis.total_pl': '总盈亏',
    'mockup.analysis.strategy': '策略',
    'mockup.analysis.strategy_val': '回调测试',
    'mockup.analysis.mae_mfe': '最大不利/有利变动',
    'mockup.analysis.rating': '交易评分',
    'mockup.analysis.tp': '止盈目标',
    'mockup.analysis.sl': '止损位',
    'mockup.analysis.autosaved': '已自动保存',
    'mockup.analysis.annotation1': '检查您的入场和出场点',
    'mockup.analysis.annotation2': '输入您的止盈目标和止损位',
    'mockup.analysis.annotation3': '开始记录日志',
    'mockup.analysis.mistakes': '错误',
    'mockup.analysis.opportunities': '机会',
    'mockup.analysis.habits': '习惯',
    'mockup.analysis.mistake1': '入场过晚',
    'mockup.analysis.mistake2': '过早止盈',
    'mockup.analysis.opp1': '缺口推进',
    'mockup.analysis.habit1': '睡眠良好',
    'mockup.analysis.running_pl': '累计盈亏',
    'mockup.analysis.note_placeholder': '"价格触及流动性扫荡区并显示出强烈的拒绝信号。在 15 分钟回调测试时入场，信心十足..."',
    'mockup.journal.month': '二月 2026',
    'mockup.journal.today': '今天',
    'mockup.journal.total_pl': '总盈亏',
    'mockup.journal.total_trades': '总交易数',
    'mockup.journal.trades_count': '笔交易',
    'mockup.journal.trades': '笔交易',
    'mockup.journal.all_time': '所有日期',
    'mockup.journal.sun': '日',
    'mockup.journal.mon': '一',
    'mockup.journal.tue': '二',
    'mockup.journal.wed': '三',
    'mockup.journal.thu': '四',
    'mockup.journal.fri': '五',
    'mockup.journal.sat': '六',
    'mockup.journal.february': '二月',
    'mockup.journal.annotation1': '可视化您的每日表现',
    'mockup.journal.annotation2': '追踪您的交易习惯与错误',
    'mockup.notebook.new_folder': '新建文件夹',
    'mockup.notebook.new_note': '新建笔记',
    'mockup.notebook.folders': '文件夹',
    'mockup.notebook.all_notes': '所有笔记',
    'mockup.notebook.folder1': '交易笔记',
    'mockup.notebook.folder2': '季度目标',
    'mockup.notebook.folder3': '行动计划',
    'mockup.notebook.trading_notes': '交易笔记',
    'mockup.notebook.quarterly_goals': '季度目标',
    'mockup.notebook.action_plans': '行动计划',
    'mockup.notebook.daily_journal': '每日日志',
    'mockup.notebook.weekly_review': '每周复盘',
    'mockup.notebook.monthly_summary': '每月总结',
    'mockup.notebook.daily_logs': '每日日志',
    'mockup.notebook.weekly_reviews': '每周复盘',
    'mockup.notebook.monthly_summaries': '每月总结',
    'mockup.notebook.chart_analysis': '图表分析',
    'mockup.notebook.templates': '模板库',
    'mockup.notebook.tags': '标签',
    'mockup.notebook.tag_high_win': '高胜率',
    'mockup.notebook.tag_fomo': 'FOMO',
    'mockup.notebook.trash': '回收站',
    'mockup.notebook.search': '搜索笔记 (F6)',
    'mockup.notebook.search_placeholder': '搜索笔记',
    'mockup.notebook.select_all': '全选',
    'mockup.notebook.created_at': '创建于',
    'mockup.notebook.updated_at': '更新于',
    'mockup.notebook.autosave': '自动保存',
    'mockup.notebook.link_trades': '关联交易',
    'mockup.notebook.add_tag': '添加标签',
    'mockup.notebook.save_template': '存为模板',
    'mockup.notebook.save_as_template': '存为模板',
    'mockup.notebook.body': '正文',
    'mockup.notebook.h1': '标题 1',
    'mockup.notebook.h2': '标题 2',
    'mockup.notebook.key_insight': '关键洞察',
    'mockup.notebook.insight_desc': '等待确认比盲目预测入场要稳健得多。在流动性被扫荡后，订单流的转变是入场的最佳时机。',
    'mockup.notebook.emotional_state': '情绪状态：冷静，专注。没有因为之前的亏损而急于入场。严格遵守了交易计划中的风险参数。',
    'mockup.notebook.ai_insight': 'AI 策略洞察',
    'mockup.notebook.ai_suggest': '建议添加 "流动性扫荡"',
    'mockup.notebook.ai_suggestion': '建议添加 "流动性扫荡"',
    'mockup.notebook.annotation1': '沉浸式富文本编辑器',
    'mockup.notebook.annotation2': '一键关联您的实盘交易',
    'mockup.notebook.note1_title': '发发发',
    'mockup.notebook.note2_title': '2026-03-01 复盘',
    'mockup.notebook.note3_title': '季度交易目标设定',
    'mockup.notebook.note4_title': '突破策略优化方案',
    'mockup.notebook.note5_title': '心理状态追踪',
    'mockup.notebook.note_content1': '今天在 1000SATS/USDT 的 15 分钟图表上观察到了一个完美的流动性扫荡模式。',
    'mockup.notebook.note_content2': '价格触及了之前的波动高点，然后迅速回落，形成了一个强烈的看跌拒绝信号。我在回调测试 50% 斐波那契位时入场做空。',
    'mockup.notebook.content_p1': '今天在 1000SATS/USDT 的 15 分钟图表上观察到了一个完美的流动性扫荡模式。',
    'mockup.notebook.content_p2': '价格触及了之前的波动高点，然后迅速回落，形成了一个强烈的看跌拒绝信号。我在回调测试 50% 斐波那契位时入场做空。',
    'mockup.notebook.content_insight': '等待确认比盲目预测入场要稳健得多。在流动性被扫荡后，订单流的转变是入场的最佳时机。',
    'mockup.notebook.content_p3': '情绪状态：冷静，专注。没有因为之前的亏损而急于入场。严格遵守了交易计划中的风险参数。',
    'mockup.reports.title': '表现报告',
    'mockup.reports.filter': '筛选',
    'mockup.reports.generate': '生成报告',
    'mockup.reports.export': '导出 PDF',
    'mockup.reports.stats_title': '报表统计',
    'mockup.reports.best_month': '最佳月份',
    'mockup.reports.best_month_sub': '历史最佳表现',
    'mockup.reports.best_month_desc': '历史最佳表现',
    'mockup.reports.worst_month': '最差月份',
    'mockup.reports.worst_month_sub': '最大回撤周期',
    'mockup.reports.worst_month_desc': '最大回撤周期',
    'mockup.reports.avg_month': '月均盈亏',
    'mockup.reports.avg_monthly': '月均盈亏',
    'mockup.reports.avg_month_sub': '平均基准水平',
    'mockup.reports.avg_monthly_desc': '平均基准水平',
    'mockup.reports.stats_data': '统计数据 (所有日期)',
    'mockup.reports.detailed_stats': '统计数据',
    'mockup.reports.total_pl': '总盈亏',
    'mockup.reports.avg_hold_loss': '平均持仓时间 (亏损)',
    'mockup.reports.avg_hold_even': '平均持仓时间 (持平)',
    'mockup.reports.avg_vol': '日均交易量',
    'mockup.reports.avg_daily_vol': '日均交易量',
    'mockup.reports.avg_win': '平均盈利',
    'mockup.reports.avg_trade_pl': '每笔平均盈亏',
    'mockup.reports.avg_pl_per_trade': '每笔平均盈亏',
    'mockup.reports.avg_loss': '平均亏损',
    'mockup.reports.pf': '盈亏比 (PF)',
    'mockup.reports.profit_factor': '盈亏比 (PF)',
    'mockup.reports.total_trades': '总交易笔数',
    'mockup.reports.open_trades': '持仓中',
    'mockup.reports.open_positions': '持仓中',
    'mockup.reports.win_trades': '盈利笔数',
    'mockup.reports.winning_trades': '盈利笔数',
    'mockup.reports.total_days': '总交易天数',
    'mockup.reports.loss_trades': '亏损笔数',
    'mockup.reports.losing_trades': '亏损笔数',
    'mockup.reports.win_days': '盈利天数',
    'mockup.reports.winning_days': '盈利天数',
    'mockup.reports.even_trades': '持平笔数',
    'mockup.reports.loss_days': '亏损天数',
    'mockup.reports.losing_days': '亏损天数',
    'mockup.reports.max_win_streak': '最大连胜',
    'mockup.reports.even_days': '持平天数',
    'mockup.reports.max_loss_streak': '最大连败',
    'mockup.reports.recorded_days': '记录天数',
    'mockup.reports.commissions': '手续费总额',
    'mockup.reports.total_fees': '手续费总额',
    'mockup.reports.max_win_days': '最长连红天数',
    'mockup.reports.max_green_streak': '最长连红天数',
    'mockup.reports.swap': '隔夜费',
    'mockup.reports.overnight_fees': '隔夜费',
    'mockup.reports.max_loss_days': '最长连黑天数',
    'mockup.reports.max_red_streak': '最长连黑天数',
    'mockup.reports.max_win': '最大单笔盈利',
    'mockup.reports.avg_daily_pl': '日均盈亏',
    'mockup.reports.max_loss': '最大单笔亏损',
    'mockup.showcase.integrations': '已验证导入计划',
    'mockup.showcase.see_all': '查看所有集成',
    'mockup.showcase.import': '导入交易',
    'mockup.showcase.dashboard': '仪表盘',
    'mockup.showcase.edit_layout': '编辑布局',
    'mockup.showcase.recent_shared': '您最近分享的交易',
    'mockup.showcase.largest_gain': '最大盈利',
    'mockup.showcase.total_gain_loss': '总盈亏额',
    'mockup.showcase.k_ratio': 'K 比率',
    'mockup.showcase.hourly': '分时统计',
    'mockup.showcase.search': '搜索',
    'mockup.showcase.plan_gold': '段位: 黄金',
    'mockup.showcase.days_30': '30 天',
    'mockup.showcase.days_60': '60 天',
    'mockup.showcase.days_90': '90 天',
    'mockup.showcase.custom': '自定义',
    'mockup.showcase.today': '今天',
    'mockup.showcase.may_2024': '五月, 2024',
    'mockup.showcase.community': '交易社区',
    'mockup.showcase.new_trade': '新建交易',
    'mockup.interactive.system_title': '实时权益分析系统',
    'mockup.interactive.initial_capital': '初始资金',
    'mockup.interactive.strategy_analysis': '策略胜率多维分析',
    'mockup.interactive.live_feed': '实时数据流',
    'mockup.interactive.ai_insights': 'AI 智能决策洞察',
    'mockup.interactive.insight1': '核心错误：执行犹豫',
    'mockup.interactive.insight2': '高胜率设置：斐波那契回撤 (67%)',
    'mockup.interactive.insight3': '优化提示：严格执行进场标准',
    'mockup.interactive.strategy1': '斐波那契回撤',
    'mockup.interactive.strategy2': '支撑位反弹',
    'mockup.interactive.strategy3': '突破策略',
    'mockup.interactive.strategy4': '新闻事件',
    'mockup.interactive.strategy5': '缺口回补',
    'mockup.interactive.strategy6': '趋势回调',
    'mockup.interactive.strategy7': '流动性扫荡',
    'mockup.interactive.strategy8': '趋势跟随',
    'mockup.reports.equity_curve_title': '每日累计净盈亏 (资金曲线)',
    'mockup.reports.daily_pl_title': '每日净盈亏',
    'mockup.reports.hours': '小时',
    'mockup.reports.minutes': '分',
    'playbook.title': '交易策略库',
    'playbook.search': '搜索策略... (F6)',
    'playbook.create': '创建新策略',
    'playbook.learn_more': '了解更多',
    'playbook.trades': '笔交易',
    'playbook.private': '私有',
    'playbook.public': '公开',
    'playbook.win_rate': '胜率',
    'playbook.net_pl': '净盈亏',
    'playbook.view_details': '查看详情',
    'playbook.sort': '排序:',
    'playbook.all_categories': '所有类别',
    'playbook.long_only': '仅做多',
    'playbook.short_only': '仅做空',
    'playbook.define_edge': '定义您的优势',
    'playbook.strat.breakout.title': '突破策略',
    'playbook.strat.breakout.desc': '当价格带量突破关键阻力位时入场。',
    'playbook.strat.gap.title': '缺口推进',
    'playbook.strat.gap.desc': '针对盘前跳空高开股票的日内交易策略。',
    'playbook.strat.sweep.title': '流动性扫荡',
    'playbook.strat.sweep.desc': '在波动高/低点上方的止损被触发后的反转设置。',
    'playbook.strat.bounce.title': '支撑位反弹',
    'playbook.strat.bounce.desc': '在经过验证的需求区或支撑位买入。',
    'playbook.strat.pullback.title': '趋势回调',
    'playbook.strat.pullback.desc': '在价格回调至均衡位置后，顺应趋势方向入场。',
    'auth.login.title': '欢迎回到 TradeGrail',
    'auth.login.desc': '继续您的系统化交易之路，充满信心。',
    'auth.login.email_label': '邮箱或用户名',
    'auth.login.password_label': '密码',
    'auth.login.forgot_password': '忘记密码？',
    'auth.login.submit': '登录',
    'auth.login.no_account': '还没有账号？',
    'auth.login.create_account': '创建账号',
    'auth.signup.title': '激活您的个人 AI 分析师',
    'auth.signup.desc': '您的系统化交易之路从现在开始。',
    'auth.signup.first_name_label': '名字',
    'auth.signup.email_label': '邮箱',
    'auth.signup.username_label': '用户名',
    'auth.signup.password_label': '密码',
    'auth.signup.agree_terms': '我同意',
    'auth.signup.terms_link': '条款和条件',
    'auth.signup.submit': '注册',
    'auth.signup.has_account': '已经是用户？',
    'auth.signup.sign_in': '登录',
    'auth.signup.error_terms': '请同意条款和条件',
    'auth.tags.analyze': '分析',
    'auth.tags.backtest': '回测',
    'auth.tags.ai_analyst': 'AI 分析师',
    'auth.google_button': '使用 Google 继续',
    'auth.or_divider': '或',
    'auth.login.email_placeholder': '请输入邮箱',
    'auth.login.password_placeholder': '请输入密码',
    'auth.login.error_failed': '登录失败，请检查邮箱和密码',
    'auth.login.error_google': 'Google 登录失败',
    'auth.signup.first_name_placeholder': '请输入名字',
    'auth.signup.email_placeholder': '请输入邮箱',
    'auth.signup.username_placeholder': '请输入用户名',
    'auth.signup.password_placeholder': '请输入密码',
    'auth.signup.confirm_password_label': '确认密码',
    'auth.signup.confirm_password_placeholder': '请再次输入密码',
    'auth.signup.error_password_mismatch': '两次输入的密码不一致',
    'auth.signup.error_failed': '注册失败，请稍后重试',
    'auth.signup.error_google': 'Google 注册失败',
    'auth.confirm.title': '确认邮件已发送',
    'auth.confirm.desc': '我们已将确认链接发送至',
    'auth.confirm.desc2': '请点击邮件中的链接完成注册。',
    'auth.confirm.spam': '没收到？请检查垃圾邮件文件夹。',
    'auth.confirm.resend': '重新发送确认邮件',
    'auth.confirm.resent': '确认邮件已重新发送！',
    'auth.confirm.go_login': '已完成确认？立即登录',
    'nav.features.journal.title': '交易复盘仪表盘',
    'nav.features.journal.desc': '围绕交易记录、执行质量、风险和纪律进行复盘。',
    'nav.features.backtest.title': '复盘工作流',
    'nav.features.backtest.desc': '回测和行情回放仍在规划中，当前先打磨交易后复盘流程。',
    'nav.features.spaces.title': '交易剧本 (Playbook)',
    'nav.features.spaces.desc': '系统化构建您的交易规则，实现纪律化执行。',
    'nav.features.prop.title': 'AI 复盘助手',
    'nav.features.prop.desc': '用于总结交易记录和提出复盘问题，不提供实时市场建议。',
    'nav.features.replay.title': '复盘节奏',
    'nav.features.replay.desc': '帮助交易者建立日复盘、周复盘和策略复盘的节奏。',
    'nav.features.university.title': '复盘方法',
    'nav.features.university.desc': '后续会公开记录我们如何设计交易复盘框架。',
    'nav.features.ai.title': '账户/团队流程',
    'nav.features.ai.desc': '团队、自营交易和多账户流程仍在规划中。',
    'nav.features.coming_soon': '即将推出',
    'pricing.crypto.title': '支付方式验证中',
    'pricing.crypto.desc': '当前不宣传加密货币支付。正式支付方式会在回调、安全和订单校验完成后公布。',
    'checkout.title': '结账',
    'checkout.order_summary': '订单摘要',
    'checkout.payment_details': '付款详情',
    'checkout.email': '电子邮箱',
    'checkout.card_number': '卡号',
    'checkout.expiry': '有效期',
    'checkout.cvc': 'CVC',
    'checkout.pay_now': '立即支付',
    'checkout.crypto_option': '支付方式待验证',
    'checkout.secure_payment': '支付流程验证中',
    'checkout.total': '总计',
    'checkout.back': '返回价格页面',
  },
  en: {
    'nav.features': 'Products',
    'nav.products': 'Products',
    'nav.solutions': 'Solutions',
    'nav.build_public': 'Build in Public',
    'nav.signup': 'Get Started',
    'nav.solutions.crypto': 'Crypto Traders',
    'nav.solutions.crypto.desc': 'Crypto review workflows are being validated; exchange sync is not a current public promise',
    'nav.solutions.stocks': 'Stocks / Futures Traders',
    'nav.solutions.stocks.desc': 'Import via CSV or log trades manually',
    'nav.solutions.prop': 'Prop Traders',
    'nav.solutions.prop.desc': 'Prop workflows are planned, not a current public promise',
    'nav.resources.academy': 'TradeGrail Academy',
    'nav.resources.academy.desc': 'Systematic trading courses from beginner to advanced',
    'nav.resources.tutorials': 'Tutorials',
    'nav.resources.tutorials.desc': 'Quick-start guides and feature walkthroughs',
    'nav.resources.faq': 'FAQ',
    'nav.resources.faq.desc': 'Answers to your most common questions',
    'nav.view_all': 'View All Features',
    'hero.badge': 'Trading review SaaS, built in public',
    'hero.title': 'Turn every trade into a',
    'hero.title.accent': 'reviewable decision record.',
    'hero.desc': 'TradeGrail is moving from an AI-coded prototype toward a professional trading review SaaS. The current focus is journaling, execution review, risk discipline, and careful AI-assisted summaries.',
    'hero.cta': 'Join early access',
    'hero.demo': 'Sign in',
    'hero.stats.roi': 'Avg. Monthly ROI',
    'hero.stats.profit_factor': 'Profit Factor',
    'hero.stats.traders': 'Active Traders',
    'hero.stats.volume': 'Volume Analyzed',
    'hero.stats.winrate': 'Review quality',
    'features.tag': 'CURRENT BUILD FOCUS',
    'features.title': 'Making the review workflow',
    'features.title.accent': 'solid first.',
    'features.desc': 'TradeGrail is prioritizing trade records, tags, risk discipline, review analytics, and AI-assisted summaries. Unstable features are not marketed as promises.',
    'features.bento.title': 'Built for real review habits',
    'features.bento.desc': 'We are openly refining the product boundary, copy, and feature set as the prototype becomes a tool traders can trust.',
    'features.bento.ai.title': 'AI-Assisted Review Summaries',
    'features.bento.ai.desc': 'AI helps organize trade notes, summarize behavior patterns, and prompt reflection. It does not provide trading advice or performance guarantees.',
    'features.bento.trust': 'CURRENT STAGE',
    'features.bento.trust.desc': 'Build in public, early validation, cautious access',
    'features.bento.psych.tag': 'PSYCHOLOGY ANALYSIS',
    'features.bento.security.title': 'Trust First',
    'features.bento.security.desc': 'We are cleaning up legacy auth, payment, and data boundaries. Security claims will follow verified implementation.',
    'features.bento.global.title': 'Clear Scope',
    'features.bento.global.desc': 'Manual logging and verified import flows come first. Large-scale broker sync will only be promised after validation.',
    'build.status.prototype': 'Prototype',
    'build.status.beta': 'Beta',
    'build.status.audit': 'Audit',
    'build.status.public': 'Public',
    'build.strip.tag': 'Build in Public',
    'build.strip.title': 'We will show the real process of turning TradeGrail from an AI prototype into a professional SaaS.',
    'build.strip.desc': 'Public updates can cover product boundaries, review workflows, design changes, technical risk cleanup, and early feedback. We will not fake testimonials, press logos, or maturity.',
    'mockup.title': 'Visualize Your',
    'mockup.title.accent': 'Path to Success.',
    'mockup.desc': 'Our dashboard is not just beautiful, it is powerful. Every pixel is designed to help you discover patterns and eliminate mistakes.',
    'mockup.feature1': 'Real-time Equity Curve Tracking',
    'mockup.feature2': 'Automatic Error Tagging',
    'mockup.feature3': 'Customizable Reporting Widgets',
    'mobile.tag': 'WEB FIRST',
    'mobile.title': 'Make the core web review',
    'mobile.title.accent': 'experience reliable.',
    'mobile.desc': 'The current focus is a clear desktop and mobile-browser workflow for logging, tagging, reviewing, and analyzing trades. Native apps are not a current public promise.',
    'mobile.web_cta': 'Try the web version',
    'mobile.app_status': 'Native apps are not live yet',
    'comparison.title': 'Stop Using Spreadsheets.',
    'comparison.desc': 'Spreadsheets can record outcomes, but they are weak at capturing decisions, risk, discipline, and review habits.',
    'comparison.excel.title': 'Traditional Spreadsheets',
    'comparison.excel.f1': 'Manual data entry (slow and error-prone)',
    'comparison.excel.f2': 'Static charts without deep filtering',
    'comparison.excel.f3': 'Zero psychological or emotional tracking',
    'comparison.excel.f4': 'Hard to record why rules were followed or broken',
    'comparison.excel.f5': 'Difficult to visualize equity curves',
    'comparison.grail.title': 'TradeGrail Trading Journal',
    'comparison.grail.f1': 'Manual logging and verified imports first',
    'comparison.grail.f2': 'Advanced multi-variable filtering',
    'comparison.grail.f3': 'Integrated psychology and error matrix',
    'comparison.grail.f4': 'AI-assisted review summaries and behavior patterns',
    'comparison.grail.f5': 'Performance analysis improved step by step',
    'pricing.title': 'Early Beta Pricing',
    'pricing.desc': 'TradeGrail is still moving from prototype to professional SaaS. Pricing and scope stay transparent; unverified capabilities are not packaged as formal promises.',
    'pricing.currency': '$',
    'pricing.starter.price': '0',
    'pricing.pro.price': 'TBD',
    'pricing.pro.yearly_price': 'TBD',
    'pricing.elite.price': 'Planned',
    'pricing.elite.yearly_price': 'Planned',
    'pricing.popular': 'RECOMMENDED',
    'pricing.billing.monthly': 'Monthly',
    'pricing.billing.yearly': 'Yearly',
    'pricing.billing.save': 'Save 15%',
    'pricing.plan.starter.name': 'STARTER',
    'pricing.plan.starter.desc': 'For trying manual logging and the basic review workflow.',
    'pricing.plan.pro.name': 'BETA CO-BUILD',
    'pricing.plan.pro.desc': 'For early traders willing to give feedback and help shape the review workflow.',
    'pricing.plan.elite.name': 'FUTURE',
    'pricing.plan.elite.desc': 'Team, API, white-label, and prop workflows are still planned.',
    'pricing.cta.trial': 'Apply for early access',
    'pricing.feature.manual': 'Manual Trade Entry',
    'pricing.feature.analytics': 'Basic Performance Analytics',
    'pricing.feature.account_1': '1 Trading Account',
    'pricing.feature.charts': 'Interactive Charts',
    'pricing.feature.mobile': 'Mobile browser access',
    'pricing.feature.sync': 'Import/sync under validation',
    'pricing.feature.ai_edge': 'AI-assisted review summaries',
    'pricing.feature.psych': 'Psychology & Error Tracking',
    'pricing.feature.unlimited': 'Unlimited Trading Accounts',
    'pricing.feature.filter': 'Advanced Multi-Variable Filter',
    'pricing.feature.support': 'Priority Email Support',
    'pricing.feature.white_label': 'White-label reports planned',
    'pricing.feature.api': 'API planned',
    'pricing.feature.review': 'Human review service under validation',
    'pricing.feature.prop_firm': 'Prop workflows planned',
    'pricing.feature.manager': 'Early feedback channel',
    'pricing.feature.early_access': 'Early Access to New Features',
    'pricing.feature.onboarding': 'Concierge Onboarding',
    'pricing.brokers.title': 'Import and sync claims will be made only after verification',
    'pricing.compare.title': 'Compare Plans',
    'pricing.compare.desc': 'Detailed breakdown of features across all tiers.',
    'pricing.compare.features': 'Features',
    'pricing.compare.cat.core': 'Core Features',
    'pricing.compare.cat.analytics': 'Advanced Analytics',
    'pricing.compare.cat.reporting': 'Reporting & Support',
    'pricing.compare.cat.enterprise': 'Enterprise & API',
    'pricing.trust.security.title': 'Security review',
    'pricing.trust.security.desc': 'Claims follow verification',
    'pricing.trust.globe.title': 'Transparent scope',
    'pricing.trust.globe.desc': 'No inflated coverage',
    'pricing.trust.zap.title': 'Gradual release',
    'pricing.trust.zap.desc': 'Stability first',
    'pricing.trust.users.title': 'Early co-build',
    'pricing.trust.users.desc': 'Real feedback first',
    'pricing.faq.desc': 'Honest notes for the current stage.',
    'pricing.faq.q4': 'Can I switch plans later?',
    'pricing.faq.a4': 'Yes. Formal subscription changes will be clarified after payment, permissions, and refund flows are verified.',
    'pricing.faq.q5': 'Is this a full commercial launch?',
    'pricing.faq.a5': 'No. This is a Build in Public and early beta stage focused on validating real review workflows and trust foundations.',
    'pricing.beta.badge': 'EARLY BETA',
    'pricing.beta.title': 'Why not package this as a mature SaaS yet?',
    'pricing.beta.desc': 'Because TradeGrail is still cleaning up auth, payment, data boundaries, and product scope. We will state the current capability honestly, invite a small group of early users, then open paid access gradually.',
    'pricing.future.imports': 'More import options planned',
    'pricing.future.reports': 'Professional reports planned',
    'pricing.future.teams': 'Team features planned',
    'brokers.sync': 'Seamlessly sync with your favorite platforms',
    'mobile.app_store.label': 'Native app not live',
    'mobile.google_play.label': 'Mobile browser first',
    'pricing.starter.name': 'Starter',
    'pricing.starter.desc': 'Perfect for traders just starting out.',
    'pricing.starter.cta': 'Get Started',
    'pricing.starter.f1': 'Manual entry',
    'pricing.starter.f2': 'Basic analytics',
    'pricing.starter.f3': '1 Trading account',
    'pricing.starter.f4': 'Community access',
    'pricing.pro.name': 'Pro',
    'pricing.pro.desc': 'For serious traders looking for an edge.',
    'pricing.pro.cta': 'Upgrade to Pro',
    'pricing.pro.f1': 'Import flow under validation',
    'pricing.pro.f2': 'AI-assisted review',
    'pricing.pro.f3': 'Unlimited accounts',
    'pricing.pro.f4': 'Psychology matrix',
    'pricing.pro.f5': 'Early feedback channel',
    'pricing.elite.name': 'Elite',
    'pricing.elite.desc': 'For professional and prop traders.',
    'pricing.elite.cta': 'Contact Sales',
    'pricing.elite.f1': 'API planned',
    'pricing.elite.f2': 'Human review under validation',
    'pricing.elite.f3': 'Prop workflows planned',
    'pricing.elite.f4': 'Reports planned',
    'pricing.elite.f5': 'Team workflows planned',
    'features.bento.replay.title': 'Market Replay',
    'features.bento.replay.desc': 'Practice in real market conditions without risking real capital.',
    'features.bento.psych.title': 'Psychology Matrix',
    'features.bento.psych.desc': 'Track your emotional state and identify psychological traps leading to losses.',
    'features.bento.sync.title': 'Import Roadmap',
    'features.bento.sync.desc': 'Sync capabilities will open gradually after real validation.',
    'testimonials.title': 'No fake testimonials here',
    'testimonials.desc': 'TradeGrail does not yet have enough real, consented, public customer quotes. This section explains what we are building in public instead.',
    'testimonials.note.prototype.title': 'From prototype to product',
    'testimonials.note.prototype.desc': 'We will show the real process of moving from an AI-coded prototype toward a launchable SaaS.',
    'testimonials.note.trust.title': 'Trust risks first',
    'testimonials.note.trust.desc': 'Legacy auth, payment, diagnostics, secret naming, and data boundaries are priority cleanup items.',
    'testimonials.note.scope.title': 'No premature promises',
    'testimonials.note.scope.desc': 'Broker sync, API, mobile apps, white-label, and institutional features will be marketed only after validation.',
    'testimonials.note.beta.title': 'Early co-build',
    'testimonials.note.beta.desc': 'Early feedback will shape trade logging, review flows, and AI summary behavior.',
    'testimonials.community.title': 'Help make the review workflow real',
    'testimonials.community.desc': 'We welcome early traders who can tell us which review flows are genuinely useful and which only look impressive.',
    'testimonials.quote1': 'Early feedback in progress.',
    'testimonials.quote2': 'Early feedback in progress.',
    'testimonials.quote3': 'Early feedback in progress.',
    'testimonials.quote4': 'Early feedback in progress.',
    'testimonials.quote5': 'Early feedback in progress.',
    'testimonials.quote6': 'Early feedback in progress.',
    'testimonials.quote7': 'Early feedback in progress.',
    'testimonials.quote8': 'Early feedback in progress.',
    'testimonials.quote9': 'Early feedback in progress.',
    'faq.title': 'Common Questions',
    'faq.q1': 'Which brokers do you support?',
    'faq.a1': 'We are not marketing large-scale broker auto-sync yet. Manual logging and CSV/import flows come first; each integration will be announced only after it is stable.',
    'faq.q2': 'Is my data secure?',
    'faq.a2': 'Trading data is the core trust asset. We are currently cleaning up auth, payment, and data boundaries; public security language will follow CTO verification.',
    'faq.q3': 'Can I cancel anytime?',
    'faq.a3': 'During early beta, access stays low-friction. Formal subscription and cancellation flows will be explained after payment verification.',
    'footer.cta.tag': 'Build in Public',
    'footer.cta.title': 'Join the early TradeGrail co-build',
    'footer.cta.desc': 'If you currently review trades with spreadsheets, screenshots, or scattered notes, try the early version and help us make the real review workflow stronger.',
    'footer.cta.button': 'Join early access',
    'footer.product': 'Product',
    'footer.company': 'Company',
    'footer.support': 'Support',
    'footer.legal': 'Legal Info',
    'footer.disclaimer1': 'TradeGrail is a comprehensive suite of research, analysis, and trading tools designed to assist traders and investors in making their own decisions. We do not provide recommendations regarding specific securities to buy or sell, and we do not offer trading or investing advice. Trading carries significant risk and may not be suitable for every investor. There is a possibility of losing all or more than the initial investment.',
    'footer.disclaimer2': 'TradeGrail is currently in early beta and built in public. This site does not use fake testimonials, fake avatars, or unverified media endorsements.',
    'footer.copyright': '© 2026 TradeGrail - All Rights Reserved.',
    'footer.download.appstore': 'Native app not live',
    'footer.download.googleplay': 'Mobile browser first',
    'footer.product.analytics': 'Analytics',
    'footer.product.replay': 'Review Workflow',
    'footer.product.assistant': 'AI Review Assistant',
    'footer.product.brokers': 'Import Roadmap',
    'footer.product.pricing': 'Pricing',
    'footer.product.whatsnew': "What's New",
    'footer.company.about': 'About',
    'footer.company.reviews': 'Early Feedback',
    'footer.company.blog': 'Build in Public',
    'footer.company.affiliate': 'Partnerships not open yet',
    'footer.support.help': 'Help Center',
    'footer.support.contact': 'Contact Us',
    'footer.support.tutorials': 'Tutorials planned',
    'footer.support.howto': 'How-to guides planned',
    'footer.support.glossary': 'Glossary planned',
    'footer.legal.terms': 'Terms and Conditions',
    'footer.legal.billing': 'Billing and Refund',
    'footer.legal.risk': 'Risk Disclosure',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.beta_note': 'Early beta: native apps are not live, and some capabilities are still being validated.',
    'features.showcase.tag': 'FEATURE HIGHLIGHTS',
    'features.showcase.dashboard.label': 'Dashboard',
    'features.showcase.dashboard.title': 'Comprehensive Trading Overview',
    'features.showcase.dashboard.desc': 'Track account performance, risk status, and AI-assisted review summaries.',
    'features.showcase.analytics.label': 'Analytics',
    'features.showcase.analytics.title': 'Precision Trading Analysis',
    'features.showcase.analytics.desc': 'Review every execution and observe strategy, risk, and behavior patterns.',
    'features.showcase.journal.label': 'Journal',
    'features.showcase.journal.title': 'Interactive Trading Journal',
    'features.showcase.journal.desc': 'A workspace for recording and reviewing trades. Import and sync support will open only after validation.',
    'features.showcase.notebook.label': 'Notebook',
    'features.showcase.notebook.title': 'Smart Trading Notes',
    'features.showcase.notebook.desc': 'Record thoughts, emotions, and market context for every trade with rich text and image support.',
    'features.showcase.reporting.label': 'Reports',
    'features.showcase.reporting.title': 'Automated Performance Reports',
    'features.showcase.reporting.desc': 'Reporting is still being refined, with personal review prioritized over external presentation.',
    'features.showcase.backtesting.label': 'Backtesting',
    'features.showcase.backtesting.title': 'Review and Backtesting Roadmap',
    'features.showcase.backtesting.desc': 'Backtesting is planned and is not presented as a current formal promise.',
    'features.showcase.replay.label': 'Replay',
    'features.showcase.replay.title': 'Market Replay Simulator',
    'features.showcase.replay.desc': 'Market replay is planned; the current focus is post-trade review.',
    'features.showcase.playbook.label': 'Playbook',
    'features.showcase.playbook.title': 'Trading Playbook',
    'features.showcase.playbook.desc': 'Define your setups, rules, and risk parameters in a centralized, actionable playbook.',
    'features.showcase.cta.try': 'Try Now',
    'features.showcase.cta.docs': 'View Docs',
    'mockup.dashboard.rank': 'TRADER RANK',
    'mockup.dashboard.gold': 'Gold',
    'mockup.dashboard.next_rank': 'Progress to next rank',
    'mockup.dashboard.platinum': 'Platinum',
    'mockup.dashboard.leaderboard': 'View Global Leaderboard',
    'mockup.dashboard.risk_status': 'Risk Status: OK',
    'mockup.dashboard.safe': 'OK',
    'mockup.dashboard.risk_desc': 'You are trading within limits.',
    'mockup.dashboard.today_pl': "Today's P&L",
    'mockup.dashboard.limit': 'Limit',
    'mockup.dashboard.net_pl': 'NET P&L',
    'mockup.dashboard.win_rate': 'WIN RATE',
    'mockup.dashboard.profit_factor': 'PROFIT FACTOR',
    'mockup.dashboard.equity_curve': 'Equity Curve',
    'mockup.dashboard.initial': 'Initial',
    'mockup.dashboard.current_level': 'CURRENT LEVEL',
    'mockup.dashboard.weekly_goal': 'WEEKLY GOAL',
    'mockup.dashboard.goal_achieved': 'GOAL HIT!',
    'mockup.dashboard.current': 'CURRENT',
    'mockup.dashboard.target': 'TARGET',
    'mockup.dashboard.total_xp': 'Total Lifetime XP',
    'mockup.dashboard.view_history': 'View History',
    'mockup.dashboard.todo': 'ACTION ITEMS',
    'mockup.dashboard.discipline': 'DISCIPLINE STREAK',
    'mockup.dashboard.ai_insights': 'AI Insights',
    'mockup.dashboard.strategy_perf': 'Strategy Performance',
    'mockup.dashboard.good_morning': 'Good morning, Trader! 👋',
    'mockup.dashboard.add_trade': 'Add Trade',
    'mockup.dashboard.charts': 'Charts',
    'mockup.dashboard.playbook': 'Playbook',
    'mockup.dashboard.psychology': 'Psychology',
    'mockup.dashboard.social': 'Social Plaza',
    'mockup.dashboard.academy': 'Academy',
    'mockup.dashboard.notifications': 'Notifications',
    'mockup.dashboard.friends': 'Friends',
    'mockup.dashboard.guide': 'Guide Mode',
    'mockup.dashboard.dark_mode': 'Dark Mode',
    'mockup.dashboard.language': 'Language',
    'mockup.dashboard.journal': 'Journal',
    'mockup.dashboard.reports': 'Reports',
    'mockup.dashboard.notebook': 'Notebook',
    'mockup.dashboard.calendar': 'Calendar',
    'mockup.dashboard.all_time': 'All Time',
    'mockup.dashboard.all_accounts': 'All Accounts',
    'mockup.market.tokyo': 'Tokyo',
    'mockup.market.london': 'London',
    'mockup.market.new_york': 'New York',
    'mockup.market.closed': 'Closed',
    'mockup.market.open': 'Open',
    'mockup.analysis.tag_reviewed': 'Mark as Reviewed',
    'mockup.analysis.replay': 'Replay',
    'mockup.analysis.share': 'Share',
    'mockup.analysis.net_pl': 'Net P/L',
    'mockup.analysis.live': 'LIVE',
    'mockup.analysis.direction': 'Direction',
    'mockup.analysis.long': 'Long',
    'mockup.analysis.short': 'Short',
    'mockup.analysis.contracts': 'Contracts',
    'mockup.analysis.total_pl': 'Total P/L',
    'mockup.analysis.strategy': 'Strategy',
    'mockup.analysis.strategy_val': 'Retest',
    'mockup.analysis.mae_mfe': 'MAE / MFE',
    'mockup.analysis.rating': 'Trade Rating',
    'mockup.analysis.tp': 'Take Profit',
    'mockup.analysis.sl': 'Stop Loss',
    'mockup.analysis.autosaved': 'Autosaved',
    'mockup.analysis.annotation1': 'Check your entry and exit points',
    'mockup.analysis.annotation2': 'Enter your TP and SL levels',
    'mockup.analysis.annotation3': 'Start Journaling',
    'mockup.analysis.mistakes': 'Mistakes',
    'mockup.analysis.opportunities': 'Setups',
    'mockup.analysis.habits': 'Habits',
    'mockup.analysis.mistake1': 'Late Entry',
    'mockup.analysis.mistake2': 'Early Exit',
    'mockup.analysis.opp1': 'Gap Push',
    'mockup.analysis.habit1': 'Good Sleep',
    'mockup.analysis.running_pl': 'Running P&L',
    'mockup.analysis.note_placeholder': '"Price hit liquidity sweep zone and showed strong rejection. Entered on 15m retest, high confidence..."',
    'mockup.journal.month': 'February 2026',
    'mockup.journal.today': 'Today',
    'mockup.journal.total_pl': 'Total P/L',
    'mockup.journal.total_trades': 'Total Trades',
    'mockup.journal.trades_count': 'Trades',
    'mockup.journal.trades': 'Trades',
    'mockup.journal.all_time': 'All Time',
    'mockup.journal.sun': 'Sun',
    'mockup.journal.mon': 'Mon',
    'mockup.journal.tue': 'Tue',
    'mockup.journal.wed': 'Wed',
    'mockup.journal.thu': 'Thu',
    'mockup.journal.fri': 'Fri',
    'mockup.journal.sat': 'Sat',
    'mockup.journal.february': 'February',
    'mockup.journal.annotation1': 'Visualize your daily performance',
    'mockup.journal.annotation2': 'Track your habits and mistakes',
    'mockup.notebook.new_folder': 'New Folder',
    'mockup.notebook.new_note': 'New Note',
    'mockup.notebook.folders': 'Folders',
    'mockup.notebook.all_notes': 'All Notes',
    'mockup.notebook.folder1': 'Trading Notes',
    'mockup.notebook.folder2': 'Quarterly Goals',
    'mockup.notebook.folder3': 'Action Plans',
    'mockup.notebook.trading_notes': 'Trading Notes',
    'mockup.notebook.quarterly_goals': 'Quarterly Goals',
    'mockup.notebook.action_plans': 'Action Plans',
    'mockup.notebook.daily_journal': 'Daily Journal',
    'mockup.notebook.weekly_review': 'Weekly Review',
    'mockup.notebook.monthly_summary': 'Monthly Summary',
    'mockup.notebook.daily_logs': 'Daily Logs',
    'mockup.notebook.weekly_reviews': 'Weekly Reviews',
    'mockup.notebook.monthly_summaries': 'Monthly Summaries',
    'mockup.notebook.chart_analysis': 'Chart Analysis',
    'mockup.notebook.templates': 'Templates',
    'mockup.notebook.tags': 'Tags',
    'mockup.notebook.tag_high_win': 'High Win Rate',
    'mockup.notebook.tag_fomo': 'FOMO',
    'mockup.notebook.trash': 'Trash',
    'mockup.notebook.search': 'Search Notes (F6)',
    'mockup.notebook.search_placeholder': 'Search Notes',
    'mockup.notebook.select_all': 'Select All',
    'mockup.notebook.created_at': 'Created at',
    'mockup.notebook.updated_at': 'Updated at',
    'mockup.notebook.autosave': 'Autosave',
    'mockup.notebook.link_trades': 'Link Trades',
    'mockup.notebook.add_tag': 'Add Tag',
    'mockup.notebook.save_template': 'Save Template',
    'mockup.notebook.save_as_template': 'Save as Template',
    'mockup.notebook.body': 'Body',
    'mockup.notebook.h1': 'Heading 1',
    'mockup.notebook.h2': 'Heading 2',
    'mockup.notebook.key_insight': 'Key Insight',
    'mockup.notebook.insight_desc': 'Waiting for confirmation is much more robust than blind prediction. Order flow shift after liquidity sweep is the best entry time.',
    'mockup.notebook.emotional_state': 'Emotional state: Calm, focused. No FOMO after previous losses. Strictly followed risk parameters.',
    'mockup.notebook.ai_insight': 'AI Strategy Insight',
    'mockup.notebook.ai_suggest': 'Suggest adding "Liquidity Sweep"',
    'mockup.notebook.ai_suggestion': 'Suggest adding "Liquidity Sweep"',
    'mockup.notebook.annotation1': 'Immersive Rich Text Editor',
    'mockup.notebook.annotation2': 'Link your live trades with one click',
    'mockup.notebook.note1_title': 'Trade Review',
    'mockup.notebook.note2_title': '2026-03-01 Review',
    'mockup.notebook.note3_title': 'Quarterly Goal Setting',
    'mockup.notebook.note4_title': 'Breakout Strategy Optimization',
    'mockup.notebook.note5_title': 'Psychology Tracking',
    'mockup.notebook.note_content1': 'Observed a perfect liquidity sweep pattern on the 15m chart of 1000SATS/USDT today.',
    'mockup.notebook.note_content2': 'Price hit previous swing highs and quickly rejected, forming a strong bearish signal. Entered short on 50% fib retest.',
    'mockup.notebook.content_p1': 'Observed a perfect liquidity sweep pattern on the 15m chart of 1000SATS/USDT today.',
    'mockup.notebook.content_p2': 'Price hit previous swing highs and quickly rejected, forming a strong bearish signal. Entered short on 50% fib retest.',
    'mockup.notebook.content_insight': 'Waiting for confirmation is much more robust than blind prediction. Order flow shift after liquidity sweep is the best entry time.',
    'mockup.notebook.content_p3': 'Emotional state: Calm, focused. No FOMO after previous losses. Strictly followed risk parameters.',
    'mockup.reports.title': 'Performance Reports',
    'mockup.reports.filter': 'Filter',
    'mockup.reports.generate': 'Generate Report',
    'mockup.reports.export': 'Export PDF',
    'mockup.reports.stats_title': 'Statistics',
    'mockup.reports.best_month': 'Best Month',
    'mockup.reports.best_month_sub': 'Best historical performance',
    'mockup.reports.best_month_desc': 'Best historical performance',
    'mockup.reports.worst_month': 'Worst Month',
    'mockup.reports.worst_month_sub': 'Max drawdown period',
    'mockup.reports.worst_month_desc': 'Max drawdown period',
    'mockup.reports.avg_month': 'Avg. Monthly P/L',
    'mockup.reports.avg_monthly': 'Avg. Monthly P/L',
    'mockup.reports.avg_month_sub': 'Average baseline level',
    'mockup.reports.avg_monthly_desc': 'Average baseline level',
    'mockup.reports.stats_data': 'Statistics (All Dates)',
    'mockup.reports.detailed_stats': 'Statistics',
    'mockup.reports.total_pl': 'Total P/L',
    'mockup.reports.avg_hold_loss': 'Avg. Hold Time (Loss)',
    'mockup.reports.avg_hold_even': 'Avg. Hold Time (Even)',
    'mockup.reports.avg_vol': 'Avg. Daily Volume',
    'mockup.reports.avg_daily_vol': 'Avg. Daily Volume',
    'mockup.reports.avg_win': 'Average Win',
    'mockup.reports.avg_trade_pl': 'Avg. Trade P/L',
    'mockup.reports.avg_pl_per_trade': 'Avg. Trade P/L',
    'mockup.reports.avg_loss': 'Average Loss',
    'mockup.reports.pf': 'Profit Factor (PF)',
    'mockup.reports.profit_factor': 'Profit Factor (PF)',
    'mockup.reports.total_trades': 'Total Trades',
    'mockup.reports.open_trades': 'Open Trades',
    'mockup.reports.open_positions': 'Open Trades',
    'mockup.reports.win_trades': 'Winning Trades',
    'mockup.reports.winning_trades': 'Winning Trades',
    'mockup.reports.total_days': 'Total Trading Days',
    'mockup.reports.loss_trades': 'Losing Trades',
    'mockup.reports.losing_trades': 'Losing Trades',
    'mockup.reports.win_days': 'Winning Days',
    'mockup.reports.winning_days': 'Winning Days',
    'mockup.reports.even_trades': 'Even Trades',
    'mockup.reports.loss_days': 'Losing Days',
    'mockup.reports.losing_days': 'Losing Days',
    'mockup.reports.max_win_streak': 'Max Win Streak',
    'mockup.reports.even_days': 'Even Days',
    'mockup.reports.max_loss_streak': 'Max Loss Streak',
    'mockup.reports.recorded_days': 'Recorded Days',
    'mockup.reports.commissions': 'Total Commissions',
    'mockup.reports.total_fees': 'Total Commissions',
    'mockup.reports.max_win_days': 'Max Green Days Streak',
    'mockup.reports.max_green_streak': 'Max Green Days Streak',
    'mockup.reports.swap': 'Swap Fees',
    'mockup.reports.overnight_fees': 'Swap Fees',
    'mockup.reports.max_loss_days': 'Max Red Days Streak',
    'mockup.reports.max_red_streak': 'Max Red Days Streak',
    'mockup.reports.max_win': 'Max Single Win',
    'mockup.reports.avg_daily_pl': 'Avg. Daily P/L',
    'mockup.reports.max_loss': 'Max Single Loss',
    'mockup.reports.max_daily_loss': 'Max Daily Loss',
    'mockup.showcase.integrations': 'Verified import roadmap',
    'mockup.showcase.see_all': 'See All Integrations',
    'mockup.showcase.import': 'Import trades',
    'mockup.showcase.dashboard': 'Dashboard',
    'mockup.showcase.edit_layout': 'Edit layout',
    'mockup.showcase.recent_shared': 'Your recent shared trades',
    'mockup.showcase.largest_gain': 'Largest Gain',
    'mockup.showcase.total_gain_loss': 'Total Gain Loss',
    'mockup.showcase.k_ratio': 'K Ratio',
    'mockup.showcase.hourly': 'Hourly',
    'mockup.showcase.search': 'Search',
    'mockup.showcase.plan_gold': 'Plan: Gold',
    'mockup.showcase.days_30': '30 days',
    'mockup.showcase.days_60': '60 days',
    'mockup.showcase.days_90': '90 days',
    'mockup.showcase.custom': 'Custom',
    'mockup.showcase.today': 'Today',
    'mockup.showcase.may_2024': 'May, 2024',
    'mockup.showcase.community': 'Community',
    'mockup.showcase.new_trade': 'New trade',
    'mockup.interactive.system_title': 'Real-time Equity Analysis System',
    'mockup.interactive.initial_capital': 'INITIAL CAPITAL',
    'mockup.interactive.strategy_analysis': 'Multi-dimensional Strategy Win Rate Analysis',
    'mockup.interactive.live_feed': 'LIVE DATA FEED',
    'mockup.interactive.ai_insights': 'AI Intelligent Decision Insights',
    'mockup.interactive.insight1': 'Core Error: Execution Hesitation',
    'mockup.interactive.insight2': 'High Win Rate Setup: Fib Retracement (67%)',
    'mockup.interactive.insight3': 'Optimization Tip: Strictly enforce entry standards',
    'mockup.interactive.strategy1': 'Fib Retracement',
    'mockup.interactive.strategy2': 'Support Bounce',
    'mockup.interactive.strategy3': 'Breakout Strategy',
    'mockup.interactive.strategy4': 'News Event',
    'mockup.interactive.strategy5': 'Gap Fill',
    'mockup.interactive.strategy6': 'Trend Pullback',
    'mockup.interactive.strategy7': 'Liquidity Sweep',
    'mockup.interactive.strategy8': 'Trend Following',
    'mockup.reports.equity_curve_title': 'Daily Cumulative Net P/L (Equity Curve)',
    'mockup.reports.daily_pl_title': 'Daily Net P/L',
    'mockup.reports.hours': 'h',
    'mockup.reports.minutes': 'm',
    'playbook.title': 'Trading Playbook',
    'playbook.search': 'Search strategy... (F6)',
    'playbook.create': 'Create New Strategy',
    'playbook.learn_more': 'Learn more',
    'playbook.trades': 'trades',
    'playbook.private': 'Private',
    'playbook.public': 'Public',
    'playbook.win_rate': 'Win Rate',
    'playbook.net_pl': 'Net P&L',
    'playbook.view_details': 'View Details',
    'playbook.sort': 'Sort:',
    'playbook.all_categories': 'All Categories',
    'playbook.long_only': 'Long Only',
    'playbook.short_only': 'Short Only',
    'playbook.define_edge': 'Define your edge',
    'playbook.strat.breakout.title': 'Breakout',
    'playbook.strat.breakout.desc': 'Taking trades when price breaks a key resistance level with volume confirmation.',
    'playbook.strat.gap.title': 'Gap and Go',
    'playbook.strat.gap.desc': 'Day trading strategy for stocks gapping up pre-market.',
    'playbook.strat.sweep.title': 'Liquidity Sweep',
    'playbook.strat.sweep.desc': 'Reversal setup after stops are triggered above/below a swing point.',
    'playbook.strat.bounce.title': 'Support Bounce',
    'playbook.strat.bounce.desc': 'Buying at a proven demand zone or support level.',
    'playbook.strat.pullback.title': 'Trend Pullback',
    'playbook.strat.pullback.desc': 'Entering in the direction of the trend after a retracement to equilibrium.',
    'auth.login.title': 'Welcome Back to TradeGrail',
    'auth.login.desc': 'Continue your path to trading with systematic confidence.',
    'auth.login.email_label': 'Email or Username',
    'auth.login.password_label': 'Password',
    'auth.login.forgot_password': 'Forgot Password?',
    'auth.login.submit': 'Sign In',
    'auth.login.no_account': "Don't have an account?",
    'auth.login.create_account': 'Create Account',
    'auth.signup.title': 'Activate Your Personal AI Analyst',
    'auth.signup.desc': 'Your path to trading with systematic confidence starts now.',
    'auth.signup.first_name_label': 'First Name',
    'auth.signup.email_label': 'Email',
    'auth.signup.username_label': 'Username',
    'auth.signup.password_label': 'Password',
    'auth.signup.agree_terms': 'I agree to the',
    'auth.signup.terms_link': 'Terms and Conditions',
    'auth.signup.submit': 'Sign Up',
    'auth.signup.has_account': 'Already a user?',
    'auth.signup.sign_in': 'Sign In',
    'auth.signup.error_terms': 'Please agree to the Terms and Conditions',
    'auth.tags.analyze': 'Analyze',
    'auth.tags.backtest': 'Backtest',
    'auth.tags.ai_analyst': 'AI Analyst',
    'auth.google_button': 'Continue with Google',
    'auth.or_divider': 'OR',
    'auth.login.email_placeholder': 'Enter your email',
    'auth.login.password_placeholder': 'Enter your password',
    'auth.login.error_failed': 'Login failed, please check your email and password',
    'auth.login.error_google': 'Google login failed',
    'auth.signup.first_name_placeholder': 'Enter your first name',
    'auth.signup.email_placeholder': 'Enter your email',
    'auth.signup.username_placeholder': 'Enter your username',
    'auth.signup.password_placeholder': 'Create a password',
    'auth.signup.confirm_password_label': 'Confirm Password',
    'auth.signup.confirm_password_placeholder': 'Confirm your password',
    'auth.signup.error_password_mismatch': 'Passwords do not match',
    'auth.signup.error_failed': 'Registration failed, please try again',
    'auth.signup.error_google': 'Google registration failed',
    'auth.confirm.title': 'Check Your Email',
    'auth.confirm.desc': 'We sent a confirmation link to',
    'auth.confirm.desc2': 'Click the link to activate your account.',
    'auth.confirm.spam': "Didn't receive it? Check your spam folder.",
    'auth.confirm.resend': 'Resend confirmation email',
    'auth.confirm.resent': 'Email resent successfully!',
    'auth.confirm.go_login': 'Already confirmed? Sign in',
    'nav.features.journal.title': 'Trading Review Dashboard',
    'nav.features.journal.desc': 'Review trade records, execution quality, risk, and discipline.',
    'nav.features.backtest.title': 'Review Workflow',
    'nav.features.backtest.desc': 'Backtesting and replay are planned; the current focus is post-trade review.',
    'nav.features.spaces.title': 'Strategy Playbook',
    'nav.features.spaces.desc': 'Build and manage your trading rules for disciplined execution.',
    'nav.features.prop.title': 'AI Review Assistant',
    'nav.features.prop.desc': 'Summarizes trade notes and prompts review questions. It does not provide real-time market advice.',
    'nav.features.replay.title': 'Review Rhythm',
    'nav.features.replay.desc': 'Help traders build daily, weekly, and strategy-level review habits.',
    'nav.features.university.title': 'Review Method',
    'nav.features.university.desc': 'We will document how the trading review framework evolves.',
    'nav.features.ai.title': 'Account / Team Workflows',
    'nav.features.ai.desc': 'Team, prop, and multi-account workflows are still planned.',
    'nav.features.coming_soon': 'COMING SOON',
    'pricing.crypto.title': 'Payment methods under validation',
    'pricing.crypto.desc': 'Crypto payment is not currently marketed. Payment methods will be announced after callback, security, and order validation are complete.',
    'checkout.title': 'Checkout',
    'checkout.order_summary': 'Order Summary',
    'checkout.payment_details': 'Payment Details',
    'checkout.email': 'Email Address',
    'checkout.card_number': 'Card Number',
    'checkout.expiry': 'Expiry Date',
    'checkout.cvc': 'CVC',
    'checkout.pay_now': 'Pay Now',
    'checkout.crypto_option': 'Payment method under validation',
    'checkout.secure_payment': 'Payment flow under review',
    'checkout.total': 'Total',
    'checkout.back': 'Back to Pricing',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('zh');

  useEffect(() => {
    localStorage.setItem('language', 'zh');
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
